# name: Vector
# version: 2.4.2
# scop: inline
# CubKit build info:
# CubKit source sha256: d20eb73e4b036b4cd26136bdbaf5055642c0d028783f7fadbaffc102b7945e77
# CubKit payload sha256: f7b5dcb5ad63ff3083ccf41c2d72f28c65219e961edff0c675cfb31db23fe58f
# CubKit source map:
# - generated line 439 -> VectorMain.py:1
# - bundled files are extracted from the CubKit payload at import time:
#   - BuilderPage/AntiVirusPage.py -> AntiVirusPage.py:1 (lines: 83, sha256: 0d77367ca5b9ac05052814453ee6106b9723728b20c22bf7778fb29e925eef48)
#   - BuilderPage/DiscussionPage.py -> DiscussionPage.py:1 (lines: 47, sha256: 3e0713bcccf3dc931dc4dad661d810d96f616427725503f71cf0ebfe3b8d0d77)
#   - BuilderPage/InstallPage.py -> InstallPage.py:1 (lines: 79, sha256: 84b9894bdabc5233e66014363732744b419e98405a1b577259bb995267fd497a)
#   - BuilderPage/MainPage.py -> MainPage.py:1 (lines: 374, sha256: c65004a8769422fec8cbbe6c2d7f29398730b44d2b3167b8ff437113e0de80c2)
#   - BuilderPage/__init__.py -> __init__.py:1 (lines: 0, sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
#   - Button/CallbackButtonHandler.py -> CallbackButtonHandler.py:1 (lines: 427, sha256: 297ffb2d26f043119684517928f5b798b3eb9cbf69d566de2da6b257cafe2503)
#   - Button/InputButtonHandler.py -> InputButtonHandler.py:1 (lines: 54, sha256: 471685eacb1e765ad3f2b1f86edebd1a7a85bff6b71014788b1389edae4e60e4)
#   - Button/InstallPayloadHandler.py -> InstallPayloadHandler.py:1 (lines: 124, sha256: ea13f52c76414a999f403fadf44fc67c47958df42862505da7b9eaf63a83812d)
#   - Button/__init__.py -> __init__.py:1 (lines: 0, sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
#   - Const.py -> Const.py:1 (lines: 401, sha256: 7eda110333f787c43d2a12fabd90a46c6495d7d6c224f256dc814c7035568551)
#   - Http/HttpDispatch.py -> HttpDispatch.py:1 (lines: 312, sha256: e198eb79e7f9b450cdac95b5bd7d323355bf3f1272850c7b875d2796931ac733)
#   - Http/__init__.py -> __init__.py:1 (lines: 0, sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)

from __future__ import annotations
# Generated by CubKit. Do not edit this header by hand.
# CubKit repository: https://github.com/hairpin01/CubKit
# CubKit build notes:
# - Metadata comments above were generated/normalized from cubkit.toml and entrypoint code.
# - Bundled helper files are stored below as a base85-encoded zip payload.
# - On import, CubKit verifies the payload SHA256 and extracts it into CUBKIT_CACHE_DIR or ~/.cache/cubkit.
# - CubKit import-debug comments below explain sys.path/package wiring for private relative imports.
# - Vendored libraries declared in [libs] are exposed as `cubkit.lib.<name>`.
__cubkit_module_id__ = 'vector'
__cubkit_package_dirs__ = ('Button', 'Http', 'BuilderPage')
__cubkit_lib_dir__ = '_cubkit_lib'
__cubkit_bundle_sha256__ = 'f7b5dcb5ad63ff3083ccf41c2d72f28c65219e961edff0c675cfb31db23fe58f'
__cubkit_bundle_b85__ = """
P)h>@6aWAK2mk;8Apk@5`sT_5007tw000~S002UDX>4R=a!_GsWiLT)bZJ&;a&>c1VP|D7aCyB}O^@3)5WV|X5b8k|pt{@bO^7#W
bLydKfdaXB1%j3+n^}r<NXp4#>;K*vQkM0Zbb+8c>{`Re$C)=X)Ko^-gwm>Ujp39MQJ=JNgej#Rb3!Y-
TKzzzE|^?Zh}~@7fze%ol-pvpS{0I6OFr<zY4fXc;)5`a{fiy=AL5Hp*^0nZ@`})XBV<V}FX++La&5V+QX(9$Gg6AerR2n(rDkP#
CI683TJePZ_&}^Pfd?POYEHI(<L1EKIzmH~lIU%ebRba?h@xZc?D!ZC0V`5PFX+PN_jiB3|9cnPqu{cP^9y;ie|W*z)<~RO-
u$$GcvO!npurWP4t5=%DQilqz{NPZMBM?lU<$lz4-
O6%M_xQd3DM?i@8BhOOh^kmaASbCHVEnEa*N1fP6`0F%K;m#Bj}kMuVA0FwFNJ3W_L84IV$;?%di$T>PhL(>J}2O^+!Q#b^^kefs
&DB6^}B~(=nLxbcnlh4xyi!Q4?s*q$q@L><G+_(Pn}!jDYx={1*7q{gOg))O$A|f@0{x^vbk)rG45M9gg!Pl*n8;$g_lM$VjN4mS
fYLPTZ`MP)avl^ILAk!IywfW}8@XPz)Q>j#D;X+2#GJN2+1DqeK|5B^B}zp~86xZW$r_0D1<#?Y5_BKH$ONseKg_ZUK2lL_$^il|
;B@#NzX~VIZw4*Hv`w&q+7W<_S;3MD=crRzD1WsNdwU$!aJdLIxiA5}b7a4ySlbs1(W78sGYt$n{AkmQF9+vdezSr@qdJgQmyk{_
g%Byzv6Zc(=uAD|c)fiEr`S7^-wCN=W^8ktMXyf+~KoQze}GN?pRH|4o@t%il#Aq*_$QFLug=Q@^f^ZR(nt=fOvywY4`&|F-
EbMA6_v2}{{>^G%a6?#9K?uordXdUqx)uG=FM$l~2yJ`Qv8k@r^zQ)PJhrn@)qCf{=EzMwC?G`F(?Y>74>wNPtMm8|Bbnx}nFi|K
SDGN=~#e=xc^W#E&&&NwOgl;Mn%k|VR!G%6!|t)=Jk^ABQ&15irfbIQ%q9F+FV9yp$l4idIvDS2-
al+ynqTv|?k?r;zjUex(m^Q)r+nE||56T8_a@M-w1aZam^P^j&Evvk-tWxME1_fGk=fg9toV6v^)Q|tnI(96J*Ikxp^3UGW|_647
)WsKTfZ2jNVr)L{-B(?(bEw={=Dc*isq)X<#nqG7HLMJRKKUMv|Dn6(79;Vm@rLQVurOqQ}<c$y=O=Ox;W2nSUg-
N4=5UYOyP)h>@6aWAK2mk;8Apix*wd9ln001fn0012T002UDX>4R=a!_GsWiLc&b7OULb7^mGP+@0fE^v9ZR85bYFc7`-
D=haAkWxxlJ)tF)+Fo1r(q59tGGG#KV9a8(-71^^-mziBN3yFPS`G-
0=RME7XQpUWMHnku(>8)JBCA?8hHwC7xRDC9=e;4N%6RD&Ha84EW6(S&GNCii^Rkj_O@4~ZsOF2*S*tZ-zw@2=Djy}p9>FIU1z~9
`%bexs9JV)A>AQXVXi*kRl5@jjlFQ7HC-O~!SQ6lsh>14Ml88#(N%u_>LN`C6D0*Lf;2Cu+0eQQ!d-
0i576iNLNY6q0Gy=N@QqZHLJdxXUb+i?Ph?lU_{^EfdULM#!Zx;Q*iF<biCANLveg(nl_FcN#zy_`}h^AQtCwe}=R@!K+-
&Pgwgz>41(156B6s&~SsA3;qZ|6-
p(Eso1IzGodZ0hBvqe;u91YuiVPs;s=b<*XW`L(kDG8@_o56@H!CMgB@PVwLZPDks(r2<W>iG<Flb$k<Tr)Kfi?3KO8b?0}t?%eJ
}trmTNexwty5szko+SLS@DKG;17!AX4hSnpj#EWKlRZj@;8j2o0g*qogUe^M0zo6DQ=LKr#cOCSO#AMj8^#xXfXp8Cv6GFVr^J{$
V9Jx9gjl^;_!%q_FXcLJC)5wb4MDfeOiU0J0RSIWfrm6~6#6NIg?SC=40UF*Z3BIEVyjRBDA<gGgPW=MW^fPTV-f*-
@FiWy4`;U9KF$}j-YBO}v${c-kr87`X#r9n9ndL*pj_!=p)6uTSqW2w4f5r8M0UhnAjYibvZziE`4fbe^0v`(qme-
M=Tt+Ct>f>MJob!6k*Qj}FfTh`iZZ9d%=~>FG2G=v}>`c14G0(1iYO^USn@B5bvMW*4<o-(4v(R?*OaB2-
O9KQH000080000X06<<gu>S)90F4U(02%-Q077+XY-D9}P+@0fFG+55bYX04P+@0fE^v9JR@-jlHV}Q+R}d-|rU0*+-
A5q~P%MIN&`naf#rDB91X>!|tSQo<s3b<<fA5f#Y~2iOQ9jrbhjTkKXQ)D}lB8)-
n_5Gf5?&sZHiSv33^QEGDhQfAp|)Etw?Xg|K4we=h1HGYFL=nbis{2Qg-5<Ue<h1nBi@3+-7RPueuvB`{ivi8-
0Z?A2!c$osv=(SfToxbzq2ho@;5G%fZ$@)QD!8Ef}|BIAm#oPbwax;5XGF7Dz62kl9iB<%IG=CMOtgoykJJWI3{GHl)&Kr)HOH*5
&3vWOnnfr;?m5C;FVeBJTvQca`u1;#atGOhP@CH@}VLQhYwZQi=cHLolO{hyx6mg@0iR5Xbi@|Mx#k_Tp@h$0)n=9{`Jf9>EY>X|
F~AlOkzGh7PCD6)f=a+m;R|ytPbTm%b=<-
&1#FD*em14K_BlyOAv7bN@@YIxl<2850_|U_A0cEzXd{!9v2SbZVY2n8nBHep(BA^^wXTI)?+1yb<tX$6oaUM(3`o>Hgz3~z0`)9
g4Rk`XDnk4nbLU`jh*#(3NBH70%}(!4W)X4>xF{13=W3eyFa8V@`OO&mc`ZuHv$)0Eo@<pzzz!2Ao<Z@7C4dP-
?h{SRBQl9Jek^_#D-it!TLhHGuu{<r1;aNowtt7wpyR}3Z<=m!sXdbpErfwkA<a-
ROFTnXfsATQ_^tRjDvRhCbyQ5N{`qXIFklkvXNkfsW~2y?+0cK^1#OB+k~U68hb0zY;zW=&2+Y-
lg*5Ilw)mQ3B$OZVP(A4sy@(9QH;Rx1C5+kj77qPa(MHd8-~}KzKxzN79>P0A;pf<ubLYOr+xSQ7vcLQgj0Ne`5c|5U4j@o-
GNs7IxV^U?+yvgYOO(<gmhg;SA4r(irL`+GN<pM4IxZA1q{6#-185(quDFIVtG!}b7P}{?Rydn_&AY4Pu^YT^!;-
AyqwPbO2A<)_foyeup2RkxJo|X+^nwz-SF9)?C`lL&5+8?W!k+*y(F0=t79=fU2?!=@vd!^rp5}E(NW~#%k$G8tC>4FTc617=FSU
jH_L5BXD?~)0-
Hsr+n+agm&yt*!3~B!Bm0Io*jpg4S#I;jQlz_F&+rogQ(pMYhyK=`2?r7#<E`8o2hAw3<e$oW4@Xo%$;wx8J)BtffEyeje{eq8qx
K@FsM>GNGh3X$rbYT5vFt8|3m|sN(IUK{QlM7)j>b=6G>jJ2$5BpxGuY)y)wc1VLa$7_`n;pb7(pzVp+4e;|BHt1?P_j5`WqbYE!
uPPorxOUbM*g$7`mJ0^AB0G*x_XId35bIEC~OWVf>Hck~(uy@GnqH0|XQR000O8001EXNh@c2W()uTb~FG07XSbNLUn0uWMy(tVP
|D8O<`$nP+@0fE^v9xTWycqHWL2sU!hYGtkw7&?;;5fMx4GZlA^dIEzq?0!C45hMA@okNzu!`oX`LLW`?9hij>!zOVU%2U5OkHht
CX$Gb3$W<~zst<ECy(=KD^vEAp~-f-KAHpic6v8jVETCa5-
PvXYN!zFsHUT0S;e66O($f;t$*$TZBen%&kgLNcwIq9|Ea@&5X*fZ?+5hwP3wH)RS#rbSRzOm=>3@|umrFqX1<lV`H;$EL3HY&7}
?1PX(c6HTX=AbH&~|Mh48#~*%sHF11ag`?4%Uw(2HasksdtKYyaE6461EUfeLZJy<6Qg2*uG#Z6zP*slT2$JmAV9nkpw@Ef1jU2e
XuMnqjheAcv60z9vv%K8-h?t)RJ2t)!(uU2QsxCd}?=SK9oM`c)K9EO2aEil&H2F6hyYF8A^U|H*5YENPOUHFR&lo>$TiVuX$%-
@xfy;;HVm4a=9~i39^+>||Nuqm5Viw0elJ2f#U}%}NrD?SZE}lK-
3!AbG*FW~W>4x1#$(mL5*jvuepI?nSU?Wz8F8nme)_&E*adJDZSQ^`4Et4RtD?n!NvJ53E8~piafj^rq{)`y@%vc^LHQv?9w$7<1
WsF*yo5nq~OmSLZh|0iOr*H!%RG|%xUF^gmFd3`?yNa<lP4gQtEdv4Kl*Hn9)``nfFnr`O(yfWi!QbUklQNoo;*`P7+=-
H~rq$z3w|ubiX~b5|dh8m*=MEa>;!))i4=z16q4eLWwk6k#Yqde&QPOtLc&}lMh`iRIEPO1~a-
R}(gCms2ZWFjIuf>A2%Db?|W`E%>LW@{lwJkC1rw|2ckqGnMF36(F^>D8(ujYNxlPUr45@cZS;e;zdrx7y&VpV8>(Gt*Xv5Q3hUd
8XwTdcfLQZ6En0rNr!eG=_3k?R^gCM}{i4T^$gk$o+DYb##duI5r0dh!(MfHi-1-N`T$b-
nWz+9Ly!%1^R1$#Cjbo~L6mUDxh;$A^<Y+vI7)N|T4$ImGC21lWjO3pdhQ9W=2tFOVU^(Y6N-
oGhZz{r>lCo8>pE(vv)nffos=&De4Pf+S3Wv}XkBB(S6tsIFO=#0iUzGdh6^5Ak&w>`tMTa`_5Cr>w(D-
`$}h_EpdsXXgv>`1iXG*Hi$-
9SprnJ4!UUs=~<=DB4ywaBm;#9!Bu8`Wfi+x9koW$12CZH!;S*c}oEhaVCKTC+~=>69XqaiU9{HS;?c$^nqg4g06oA>P|yC3jC#S
C>QXiP1vGW<xLqfpSN@P8ljioP%yBHI}O!}s}A<>rtq&nO6<8g?$chE?ukq<)SVvWrz&GOI#Gyp5{48@w7<xsLnxxtP_Yn&Qk+EI
RUa9-Y3JkzdcA3~rCE}!?)dUXVmR~q(j}F3OxtcBwt{p)SCDAw6AHaSjBn8<wi-J-
cK0%RKRn^lOZ8+=2|+8~nQ9Ja6X#6W!kGuQ8pLdIcIF-AATlqdnUC!oK$QM}3wb!2d_dY&1`w%*c>@vU7&8hbPOO_EWlPYn^B?D3
p20-jy%Ot?!eR4D-NP+X=y4Oc8OVuPNv5m8f|E{+7LFx{sBaxzKi&=ZLJHZW^>BaHzy>VuR07Wk;UK-
$!Z^8*;cyNplB{7`2V#(Jc@)bx$VBWqj(z)hsXl2Bg3vM}MhLB3+(~cE&<xgc4J)Aqp?*w0c-
7^dy#p_)UflB6_CS%{hODTa@gJC|y(-HbfO>yd@LP-
Q@+#o;w05pa7HkbHqpfL3cy$iQ47J)m3HdO^<vj%V^;>5+NpsPc(VVh3|61i?4n~3~>!A>#mGJ07b%ruS#&MIDgOU!fnk0?<O}$G
+BAnE0$2}a}N4Io(O`JNfgOu*g>Hzn!{G6XSA|x<UHRNk#$CCjP5i}eplEFuxN{<vpfPrdlN2-
B`UR{w92VljDN*mM$BNL1sCK@{>yrABepA0HAPHm(yab5?IVSA&Nz6i=%B-
L%(H_nCykR3TI2>v?NibjlA_f%B)`SO={zb()BiEwsxa9&^y=;a;@b#x4RhZj$%$ywcLogD7ATMM71KG6c@{ofWc*wgJ#i1Zj`a>
jgyYd(b-+Rov*-2(CCZ7Ls2oQBz`r6Eu`W+IT5KoX9!wdhiv!baL;L~OAQF)8M+CWbPXI=dQ}#=si0P`*-
SHQqs4B?reRCBlpnE64qix$sMoM}?m@p7YW<w;?T<J+_rakgd`9*lsL1ZB^qk_8N$1*M1SK*%^6)1^gF|U_n2<UN+?ERxFDgvHOC
=q;L!zXaSZKtWvN&brE0}9o0+MQ_Wx9#`+!rfYeU%lHIdCnW7qzur*ScWyErRF`HfKM}W2{1KHtKs&Fe)A=*h6=O40tD^U-
G0d&y{=btLt3G!fN`uyopQ55A!w`gic_UN)=!3mALS31P&8lp&mjE4r$Ju`wDDlSUC%lY}UEAs$6wWvtK;JFa$$I?K3FO1MPS!#w
fM7&9uRz;dXKkPkkIlHnlLS*d4uVZ0lX1<o_U!Z61)A!sFh2U)ut;-i}QGeIk#EXtnkQY2U+3*YlQB|seBCCp@36Jkr5G-
|4eqliDvppP<{vKDa_RyMk6RGRrGE2D>BD)wOhkLM9>iZQ=p>zArkvm>`D10!NO-
7*aT&#`_Y}^alxWZiz?z0Oz5@>N3K#XqkCaE`L_wliH83K10UU)+<6ixtSlSB|DViAvJW9h{pp4P`{L#X^<we%RAjB#4S3_eH?2X
@JJ3oMB7IXz(%LV}mhOuQQ#I%Dwq90#6QB_1wK1)&7U9B#_-
`OKUCnJ0jPgxWjoX{}%V2s9;p*!f3!f+Z>`s(#o}_@EHbC7u|3^{o@-
aY*Max*{erTF(FRMPd<=wcPRe6$GYOgv9&{A`y!;57C6kbn)or;F2hwlIn&lA1hlT&)onhDJ$tif{F9(x7(YbTvwL2zp}#aZrr&X
)eSfpx%76WteocR45Q1fyEdL-
x6kV`Z;H8t0l6$HwtXMDv>pDWS{CtlYG7KFPImoh+bpZWp|5EcjH!4ptrO?yr}0!%)v{GJU00J>dSSrZTOPeSgT_Y|^=5kR+*YHY
qXQuoUXswDT#xR!*E;XC4q#&(sTsx6u)DpB(KV<~^_NRX5m$8vPPe#ouO|4m0dD5b$Aek5qH+B5m?@7=?4gH^f0VjcCdZZ<tdfqr
G_@0<$u9Uu1JZy8&mUKCa)llj^mD>LQQ-Pb7RdzQU98iI^KtRf%F6N**3u;4Xv*|-
EYQ0l)}8*9cL7Quec${&KuwLGsxUZ3f1k}}=ke30k+UaDJPf=%m)a_WntcXUAsbk75MmOspxyCR)b<I;FlR5f=~o43uwQ~Eq&h;W
;yFmv;XFu!_z!k+y$p7PzU-a%D@?I-r6AaPLkw=$mg-PZvTHxVurYz?^4xPC0hvaTfj^WKkF6BoSqIN?bHCwrs%7DYpT9i|XZVHN
EIy(?X;)crJxpXVEjYEVUEDSt3U%)cd}1=t{E$V(^iki%#hx%dJlU_)18+HDg?Jc0Y>7C+HC)4&TOR3b_5920j2q{tElRJscv_@j
wdYSiJM0HsN{N<?%tV^SJE8HuP@vA&>-2MYP|nCSk4Y=q0@Gso@TvZ(eeyK-)CQ(s(WThb0m0CA2=aCe!VYu~vel#YAeW~7-
wt!UzT8%}VO6p46sUmA4>v6QoOt2XUlXoDCn0h@FjU?aRCig(lRNx^#Ai`b4<&c(8d9w}etqAyVcOBl*;b^XO3U!X_aF)pee;7+F
^#s7Q3j{K0yf@nZ^bvwOUiLUvMc<8TmP66cB>T0z-
fE4bVa9&L&d!@zLVC<B2K^)(fF27qqDx34{m~_=AcdqcEobx&>u74x7Tdp;#+I58!+{)kLP^CZWcTPru4k`l{0^H|B8Om%c9D$lv
tVgn6bVq*qC`!pFUXheS;9zZMSOoUu=bM&EA64!K+<S-
?>=GA;#7LnDK})mjKP{0N{#F7()|W2DF;@dHyEP)<;GS)H}B~(;_d%Tt^c!D0_Vq>!$6Wos3%;kCagj4IXs@4_5E6A25|VSWPd3r
0TFb!A9_J0d9ga1J5~jJEt&r9$_)0hu!IzsaOSBg@5MIf1S<B(qA_TR$+pamG$C%*}#1N1yD-^1QY-
O00;m803iSX00002000000000N0000&b!lv5WpYqqXJs#6UukY>bYEXCaCrj&P)h>@6aWAK2mk;8ApktQ5yD{#006`~0018V002U
DbaZcSFGFE$Y+_+!YeIE&bZ>4*VQyq>WpXZXdF@;2Z`(K)|L(s+&|qL0bzQgHnJtVsvuU@}EjCRC+rfTu4MCPDn`4=@MJWfe`QP_
FQq)Nwah#)r(TCRJ@%WD4J4h;F%ompHhG~+<#C0vYSn@crJjQt9C6qJKYUws{&3wxBYs9Bh%BK1?p$pOqk($q0LavgCPBb-
<E|)P8LiH!tOPHtoPS~|-
PU8rs^p;*Mi0)jaJRz;t50<y2ns`ilI4<H|K;qtl2WdpyiC0YWy(pS^{=7B;mL)=u`OG59$QR(ro5}?u4%5_(Uhe~lo#>%X%Yx_R
x6khTldm7U^35f}SHFHeIX!)U^5Ngmd3N^kKdSNc{N$gX&pu^stxl_Tdj828YL)e-
BsqnjBzElo5<lVb7tVM@lbH=eTYlsTVX2M}nJn+qB;o8|9t$E8f1y{D4O()ke`sl)j(nF!vH}uXA&-6Hrpv%fh>`&xL87p0kqg3-
K~)P~3r2baE1-
Td5=q=e(~PbES!bLPU>^UIWIEQ%WBE47snXB_yeI;BBR(+!T(P|A5@gKL;C#ID$r3TvsZR1PJ(?&Udma;)pr_6~NRWUgPNf&0(7r
)k^ge$$Kl?gr3*yE8tUbQ9jwZ*d2Xp|&5>ER9wdlrV)$ZILy_y``-
3B#@S{J}bhW0F3M1~=t>bVPCUr=&6{MCyDsg5Z`1j)LV3o2JqNM>B&g~X+ROR%?wjje2kcyes;A9%OzP8V%K!)vw3;WgK6G3gW7-
K0%E*UB_f13&?n)^KROHue*ctiB|PV;*l>69%kZwDUkV-QuMF#JwPX5apKr^Ej%C%wWS3Mzc1+>1bSx^m*hmZ$T<Ubt7W>7rPjoK
wgSm9@A-
Mc+m_K`Xw&BD@YEBKdbVgTVe1|rO^$CYkGi`wrb@X4l^O$h>8T^*uY{CfpC#K3*t8TD#$p*eBx+{JDuBaY~3WEr!0YK^8aB(n3F9
hXX$y3ptg=2fG$qJDQegrHIUwH(ID-q+|;8Iqvqg%kNquu(|_|bXk5+$<Ok_uajnoiR655-
cynyoRkC{dX||3lE#pF#Vkn;j0Q&iB=+TG-
0}E}0J~W2jQ9%ZBC*s$lOvAVed~jF@w=kzEE{s<g6FkKP9PmqqwF*u!2&5LO%!s|q^@9Oxx)iy6mGSoKM%GCV$l+*W?Ti?#P7r48
l+78uv^$U=5Zc2wm|f2-rXc{^9b5_e%Oe#%yB6Lml4~c<1v2?BJ~F|{a4j}vIYqFWX?tB-
!>5!k22HKatrzt?g88F45?FGvbOomDOkd4R0c$DNoAYZl)UZ*1oP{VTKv5f-a?`#fDg=3HkfcVx;?wqp)|-
pqc0pNg2tgt+u49sZ3w5vp^ctusU+Q_wC1HWt|0}fCM~FNuNeO5|7Iry6Dm(xxW8w+UhML(OqeQhup)T9g^h89+(s@%10YhNOfSS
D&V(TeWq!DUrP3f~P<_3_FG34gNq}gG$W2?X03YT8Ywyoeo`I1mCs;yKv{JJIbVrt_WtS(AM?gi5O#;_3MbBHo!CDsZs5IqaVCcc
1>jcLucUf>VA_XnrUQ4>akcjHDFz?D>Y2lV-_iSjCkDkoVlZp!msTJLTlh{dGBWvTEuF3O5^Tub8Yh&C(HOn*5A2+or9uvnmr^oR
KfR2eO)Y`-c+@%A`*{_n4U{+5QMAMTdz{fG;4h-|-8wGA65S5-z2U2Pwrir%$gUsdYcmD&l`sjR9bc4M#3qIpw@&t3Lo7`xy0-
vano!}c%hH`e&<uo1&&+hz=(dL1Hl*eY!<=7iNs5>Tk?`3b!suIz3aM>apKY9%WZc`8SY15{~vC-
r+v`owzI?+dwCs+WS&McpiIRMoQT!m10Js6gU#7Sid+mQD5;`aCwxVoX31@OT$nT#<$$y(-zS_;q^z2?ATlAr{qQ#K8J7$YQ6E`-
0W*M?83uDNXVX1<9(@s)IuHJx_;|)zqr<JdE#q{*1VDaxIIH3s-
RtrA54OXP%hJq7S&eb#Ew396V?4;Xh8NTzF&|1!)EDH0J42jB?7jyHoZkTL~>_n1*%3PqjjfM*&vEJWfbpn$v?t1TZujynNfQ<|l
;A95<3cqiJUottDSN^R7%KC0PAneND*H`rE(~Gk%#PQbJ1kh=uWi#Fm4xAWMOzSOwK|u7**G$^EJcHGY!PC~y%T4$|*huPctxSwC
k!39>2uZpKu%fI@8|4pfOviD=6Ws`2Pu;ca^zknrg=dhm1cM=Stnr2wGSQ?Sj|0l8XwEFcK+3FnbhjMP0aLG8MWNfNAjn^;3I&Rt
c{_&|)lbu<Jvk0e6m$eJE9h{~=J9UFAC5v5X;CQ`L^4QQpXtH=<m_%WOUn?Xyvip?&jBCVyN{$U`~gz()@ie&}utVil$0l1wX=3V
@W9B3P$8~#%R_$L3`%ftL-
^+0@CrMZho9oTEMXYS`Y#`+;AY3!xuX61UuuBMfY!x}DY9_I7K0#qa1<#gy9Ry0u80^QfyF(dxvUHLMbyes2DQhS<$d;9kGiK^_f
{^**Jp)OO4yO9GGgu4fedY~xH%+qWGA2k}=+-
?__i=WY#5_sakSq1f~38jzdynI}?P`5nY;s&OeBzv?+70vo)rhG=!t(A$&%M7aDw+4LT)0HfCZ9QMXy+!@<BRelaC3+Ewli}}i+B
}Ha=z=K?a#bm}|Kk$2vnX9ByZ=ikH3iGNpo+d2=qo0xsucEb=U;!Xg^tjE1q{DJOqcHmfeX_GU=ATekGg~_btoX#Lz<LiDE~EGz-
HEr>sP7wvgJ-@+GrJq_lkvK$W;=9c<P#6IKWdy0tI*|7&h-?K-9>hLJC}UfBooiHIlw8Y&@Z0QG-gbE0utX5}{zHZB_F!C>wdB!o
$GQw$GRxpjhA>uwyS493Yq2c>6FX3iafHYmKmLyxZ|YX{WaJRKbK>;a+%n(+^NkgTbQ!Zs4dlx7u$LaI%uu?p;=yOXw25Lr78!8=
;Z0HMH!QEcgX%AXFMxgS;RxRlbE!+`S%sW*;d1mGi!boR@zmv+1*yyX2nwS15aZNm5bwn$Il`nwIpZ6FX<6wcoQGnk_!R8&{?;Uu
yZKnkU!pH)=`d)({)-cWx0blKhJp#dZz@^}5et-(DwsIlGO7`v@r89@z!)U5H}P`D|i)Bcwk`>^?BC?_U<7rAnodydl~=dd-QoI%
>Sz?pXL9bEo|IfaLoq05T9&?QFc_*aojEQVdW7K9%GHt)1JFh4ruJQIXt#=k`#42r{E23iK^{`MX1TTV8x)T{`XaQvK&4kMO4<_d
F0lH{PT2I?QJOetCV<=MK9YO8pgx!3sOZP6^C)_E9#fp5z@m?Bk)tUQxfs`A*m5Ui6I0g6|{Z2UPfm_=?S`5D=oAnk2<kv~s?XvS
%?(VF2Ho6T#x^=QS?hYU@jwl**Vq5y>R;8Wd)7@y95Rlw(M>bWz5xq1x`W{tr+~0|XQR000O8001EXRguxnivj=uk_P|)8~^|SLU
nX>Z*DJ1Zg6#ULUnX>Z*E9oZe(m_axQRrtyN2l+b|Hm`&SIQ#4c{w_Ef@Vp@o+A(4I;!%OVteoQTMhkmNjQ``;_cjvsj}TUbE?n&
&s)%*d5dHBeeLt}#d{@LDV5fJvzwb6iQABvr5}lyrD-g0D_Cw$a+4wXNPAHJ9s??xQ>=Nm2-
AE&Rg5Df3P0#(ip>Q}Qd5r9ktYAGlm33HVcD1+?V0Xsq=~sX;A{lm{QWicYCTQRUF^ask$vY!Us!G3c>N2>N-OU>+UQ-Xff+_KqH
;eIz@&a+2<iBTxCI8TAORgP9s@!3x|cQKDIn<EK8pccRR0Nj7yUnPW?Dmij`@RMs5@E{Qh0X68r+Wj5ld;<6lLbIh#Kos$D^AHX$
Q;G@6gLG(26<*i@|9R^Sa2+1OHoo2leufR`0j5q<=kxfYMf4!#iQPxH^8hF<TTCie+C5=)$-
!ajkO|xmR;8v?LI7PduHXN^|9o`sKDpS)9vl}W|jp>Dbj7olcw|SstruGueEQi@F`}=1Q2j@;oE@EUC5>G}CWO>QS88@daBqonUW
%(ctxm)4+1b3uHF|$Wmv@K`S?$L~!-
i~+MbKIeHi?DDxgawTQki(lCnBOsfT`46ze_xoe7zg8rk~kEw=Wf%la{BpDpbl$))+x4U+_kypEuJ(a>yj+ve|CZV<{CYZeKN*Vv
@wRSCT4$Tb_L2b+GcPM@2}O;&eJV!BeEQ>Ep^Rh=x1B_Pt#y_WkGIWd4P8x?(SX}4m-R6PA`iynL`-DeyMJ}DdB}We-EO2;5}SIk
XNk*jrp%yw!VaMO0BFLB}_-f=I!VV0bc@jlD)-
!^P6(2L2XGO%VR^oa4@NC%2li~lDZwg_5T1+O9KQH000080000X0BcH8$Atv|0P+w303QGV077+ibZ>4iNp5p=VQg$rVR>wCVPr^
QZe(m_axQRrrB_>T+cp$__pjhs43#ihak{qHjJar5WNCn2f;HX4ih`h}Bb$p%sU#IA%lzMWNJ_ROyGpj|!RF=gT)uN7GgYhzV_9V
?1&k4~Dhp)@m$ES2h(hYos9sxgz0AdYJ6-Xl8Rx}fA>^W&DriPVtYDN`8A%}x+!$og$k0_;D$v^RS1QN7xa3MhL-
D0542(vP2ros$ML}%o@`9(J;#HAWIj}k39a?jfEJ5|?&20&~AvwJUX)NEoNO<lk<M<UCYZ{VZMDRPgIA_0}d^nB#?BnHY_Tlu^@2
8i3;mygrGj?(Q?yNn1Z>QmC^yd8;nKj773ovhR2r8g|Kw=8@wva_G%#tGMD9O3j#BZFV7Cg@{_^q|^HJ51)>aDmDayoKiUe*={p_
_7jD-
)7JMy}m?COiXHdJe21chvUNkY^DA3&OO<!Y+qo{DQnIBuuxIBJ*T%QJLMU{S;up$TlGcjN=@mr!%qmL_6lt&ksI7HzMs48+F@Vu-
{zBtU!eMnv41*lVF&FF9AI}y`&MLM;JIqW-*=@hKBnbD#=%XECSD~P~>hCT2}?M(xB|F<wC<)8zsshjB`JrFAuOo8$8E-
T^rP$Z72{$aAQ=^(mlzA1sZo4{tI&(cxE9gAW~Fg(v=7|36vPh?ho^HUuaw4__z)AZs(U7nG8Bccl33^fC_1ln0?IYWg{lE*iAYj
@EnFN5z+)W4#{`3uX(p8(N+oT6CZePhRj<|Xp8a0vt1^3S+6m{wsj`hVioR#weJaQBU|A)zJTDMN4<v0k{d)KA{o8gR)Ec&56Bb@
W&z8&Trgc_nYanU4c+4wev{T-j}&qg7K9H-Gm9Fc$(7MoRzM$JH`QWF!$I$q_7J+qvna8G1$2s0@U-
KW9Aw}qo!_4ga%2%H))J%1*Yb$)#9A8>qnYCC2t#QhxouA<)-l~4#S$Ca%nfK=`sz|Q?QooZuWOz-qKBpJw0FA^sT)gEAUX!L88j
IDgN%>6*dq?Oj2X~5&`shT`xX`(c_opir`wKO2V1YO^CPmpqjkBrg(??Uu3)7?yW!>`H5VIXR^|E1LKi6d>16yTAOAfW{~WXN=O1
VX3YX_Df}C$+p;NIy^M_-
`Dm~YMEd};I5Zj+1#CGGVgJ*@)7v%YHEppwOwZp;QL1GE(u76s6ItG~(DImlq8~;SZs6&Vu+Xj3yz4PGWz-zUk!wl*xQLLBz$+PF
Xy)a(F4MGFjbnBJH&MBP~D~x4eHBryBR?rVa`>;}RuuN<zb{7a&@-l#Q&XcPyrWj+U(o_7$<WRshb{soFCs2%$IjgW~<-
4UF6#KUd2mPG6I?@k{u27x<v;4fkSV5Wd1boGzWY-ctO`l9ApZCvJc(zt;=<u`NSyZkrhj@M<NIWPwaMsubr*Jc<dX*lj(5+t$Tl
)=#ZcDBGy>29S_#O_%heyvYg1)6a9wf<Z=V=0N`u}luJBaOu?#pRKx+$(e_O6Wf!es?r19RK^`RbMrCDcH=*pJTf6$R-
5mFP#jT@s;5P0_vny0;hj-hd$*v{%Ce%t}xzE)naVr2B3HbtA#s)3%3ntxR)<uQHzk%}Z!=<lUo>?%eAvsQaaL#O(3oaMP@}x<-
3f7nMqY_EggmVLiV%&(?Z%nR&G$i<ro6XTNa-
D!kV{w77COqcCgovB#H!QiY;}P*v^<?6q>wQ})*yi<XUw`mvy^xql~&S|)wvY0{BIFW!H+r2VGkUM-
3nXt1<VfLeqHVE&KrH#yal>5Q4V-&PabzbR;Ur*{S|jVTj%19>_*#{1vo$IbmYvQ3G-6o}e!Jm`-
5oNG12fA1Mw4||^e7f?$B1QY-
O00;m803iSX00002000000000I0000&b#!!ZZZBV7X>MtBUtcb8c>@4YO9KQH000080000X07zJVX^R#B08>!_00;m807GwXb963
ndA(d)ZyQN=e%G(4<pOIdV^O?FB&B%0(8!vRH@4+Sat6uRAX?2LRT0_U(-(<cTQA0BF7WIq;}|o8odt~Syd=QBNESx2EWv-F_!s6
Oi##PiA?H+8H~UJFmNs7OQ0zK&s_N7^-#O=#&`sOykb1r8xt>kyb;3H9X}d%-
4Aa$IW*W}KgnDLE|EIRuYB8fVF|m06cK!Xu^=0yFlG}1!%UPJ2+1=gE7rHxCcTGFrHru(0-
+r`FUqcz2=5@1Uu{NEwbF}x{j~A!^Nt^y%VS2tk{ph`i`QhJlQxl61HdgBE%S&s^8@S{S-
G)W#ThunUy}Cm+Ti@!K4X;g|yJlmvw@xi)whN`o^zJ7gGIz_{%uRf-
c<0Xhi%Wk8`@VN?c`dwiTieaIgqY`0TQ?1t8ZPd5#tA8!`Oxg$m5a>SwCT)jQLW+3bTnqnXpTc&X9f;GTbRvTMk_aQXLa$`?Ry{o
RhN?|SL-dpV)tQ1T<VuQ^|ofT>J}Retwx3xaucvKxSqxJ)q9CsnjrAc&Q1Pifxoo)N&j<x!q2rQYgBVg<H=wC^|QacIC%1*?HP?H
YvtLwg7M@dIkdE;*)2M?@X-
02$^3g$x$CI)_J{XY*Or&SUnZu+svFB|cT+qAmRqt+e)?pC+MOr=^~ab0{q4U!xutp3eo`&NlMTAt$y7ZxF)^XH!7}6{x@l=GdY3
ksw%oDY-m-0*_T+L`rxtql)Pgvk1+p-
wL7Svb9evWJU3Y;vu02JjZ{nvEV@(1fLByzdAWTCcYz&giO@zKp2E#B}sGAC&<ZWuTHJwi8egzxP{YvXtf167iz9EL&Zu;m=G1^K
Wy_UO%qn~(Y#_Vfi_Ak4osy{w3TK)DNvo)y#JinqDjW)HFrG$y<%wTT4KIzbQb827-
$FrzCIh7B_2MePlEUue&!&xA0=C~jG`eCg#G4Kd{;NwRV!7{YNT(Jb+E($D=#2j%y_e_H>q%M`$EQ=bAN%<8|czbE}-
ueP*Fx~wauI4)44=(&z%+JXv$}Ny<H{8}V?U?_}i1_a`Yy3JlH#=LMotv)|X6H(?^VK5!FL(3dgF>NDY|a(vjTwK=&1=`CK8o&^s
jghBRcmv#a%q09QYcnx^CeK{m8!FPimF}BHZnEUYQ<`yR4rF(v*o#Bv0SPOO%<*1&}-
5{Geutm9NlIj3bNEz3WZu>zECO_i?!l>sXSjR1?Qb@G*Xm80C&J&viDi7mMVq0`SN_BT&z~hv+~51`T5ix;^k38?`2!CG*>N`D#c
Pk9K1AJ8*GqPQgq7Hkg0FJG+Qkd=8Lsj2~1g=D-
}l4=hV@qhulti9`2@Cs1z!2)x}z6;5K?GMXR&LXgk}A^QB6)R<5BlmMie3QVjG}XfaKn*33S0wOT1x=L&^#sa623)%lwA!opmdCa
4IUVb=>rn@6W9LVOg;A@k{4iaG=+Ez|wV;CFMixw+Z-+1VNxv0N5AD;Kp)uil|HYce{-b`WpXN@)%(Seq-
93RQX9&AIGIL8peaJmlE53j8b06^ig<wNRK19a~F_WrSgL>YR{*0NX6*)X*l>F?2|vrv;F|RN95LO|5~M|H>fE@pPR!*~S>lotV)
yuMT|-NCZ~{wvG<f?=Z8CAA+E<Zf;*u6rwW7Etfv*-
b9^&9zQ3$p4Fx@FG4|eUvph*8;?X{77I`2nx?(U8UV_&<{A`i!2sz{cgt)%bl#hMxDK`1)YNq~*QTF%%%(DyV$&^VkpS-
*byB8>(m`x;hdB;h)<8ioWxA#5+fWK7R(5)hOFP6LPMHa{1Ff5YEW0*yX?(tG1KbeTB!L9M3BH~bea&XaqOG_dWgUm8;ek9e+RR9
-8_3IH0-
1;oCI#hCPIX2dW+;fkf9aZ5gs8vc>rh?mo^8W*5jdIyg#uwA`$%oUE}=56H%({*;v3!798orlLD(&r$7r$^^qLJ2v`i;_$L6kqh!
xlIfd-
$#%Dx0qnH=XnngEvt2XN}FSThFIoWRk?15;qLgQ!cxrpOsu2T>#U529TSkL=VN6k4RsHV!X(;MVp+avavi@mq8!WzcNuIA}JTOlM
j<Dc~7O1b;{qQV^ND4WF?E^iBhDIQPH-
&rK|DIdWTrpo)pWy$g{$Y%@Nz#Tuv`N8cllA!hf;mW*y(GoKU&T`9tC(43Di>eROy!eSo?hqw*V7hfJAsZOz7L$P&>>a5u#pFs21
gZs4hB(XqlU|)4JITQMBoOjPueFKCPTpW4)$zD>nEqo;R_o$n|mzKK)P7WJ~=0iFh)RshtRyKYRoUK_*xQ57x06zvo!Df$0S0d}w
hQNu<+XU!_aA3M{x}Se|L2hi`R1-
9*XtQnV+q99tF|&E|p#j6P*<Qf!<c1D`eiO`$kM?fNh_6BlTjhuhpm)cYh;E{}S=Sokde<~Or%LKguiftbA|Yyblq7<z-
i98DHeynnu2I)bs}~qEIoxPVH--|j9rJPQ(Q)wO$E?xan|bU)RoLEpl(s}e2(Fu+4F-
&Qd|T$%oTN$sX~asyPY07^9`!dS2rtqUcoUNar>N^qfgtOmPb8-
2TAnMtCGH;`tqXVU>RbMtyINO)mP4RXCSuUvW!y>NtPT~p@V_sA_;>ImKw{?h$U0>HsHo;O{D4{l>ySmS!Cdfmgtfh-
s0!32(=fp2@It}I1NDpdZ|C#*<SffJ#b)lqCzZ)|aeafhHl+!9+`CxG6QQ;4YPOrP?+z87bqDYquBnMUq=V|=26Ro|qA5FR?+7>A
*n$9X$sM{w+esnpQpDO=#(}ACY0zaPq~P|1kOw_$++l?l))M%*VY5~X5@1vUM(fZ(3l&T7$@DmKqlD_(b05JcW~iiukMH*cCOFA$
sHzqPh^R}!R6XkE$%eKKu2jTJBTn0NQ><l}b+_v(G<4)aNsEF_FznOJOPkUtpbuaWzAXqy*BEXeLR0v9ieLQ>Y6p>TAaZ&{LnoAR
fmK<Xrmv<#&%Y)|;3eWOX89DnZFx+FDj-`^(<uNv<TgzGL@+HWo=CfvjG`CkWVvf0Igx@YZ6$L?mQ26^%b`gr2-
9sT_WaM}7ISn@cxqG-h5T@QEXwRX#CPGY4L>Roqf@3KBO_z8)A0-
pN1N_2y6dFK8lH%p`=;YU@%~tcR2sh(Ay){3rGa)8Ni|R2r^MZ&q{(c@{YA<wbuUY%*KUZ~O_y+iSm6p~iL7oZ@WmY^kQ0ZM&NV1
DspBeyO}Vg5UFiAw&;Rm2C;Q}mD9e*FyS8xBpa1xKl))v*nrNvLt7^`+Top!f_ZG@_0AnEI<R2QP>0+&rp5Jk{V~BMgSgMOoU>yo
!WsOFLVgya>nh<GFDaON5h-zI~aA91~u1;wqVFQ%Y4PAKTl4j_%owSqMPF;qBOhy<4s*Gp=+-
+)35}F+d7unSc%uPE{2b&$_C!k(LIS_!D@jZ;-Fj2z<U>e=Xfl?_=ONck|)rjf-
^C9y+E67w2tcEN+<lzz<Mp5Z{>hvB?7@qZUj`ByLo~9>!6oV`z9dZeOz<q3K&KC5EUa3&3#7lLN%i(%jJ_e|&0-
5Xdob1oR4b%tSwJ49H9rc1=)-
|XL!s&%wL|vre#@LiiwxdovzQPD2o4cE6yT{iUbmi#BsuSOCz55Phy}HcaY5n=wnpIn_AS~3WlSxF#pxT@oqC<7^VI86FolJU$wg
Yn7W}6OE6Kd%(vjd9wy*mN7ELG;lKHQ*rSA|A)vp&Q-
{N^2<H?v{Sp6?mk1_+C&lt0R>K9Uz;tU9WbhlKl&rbnPn@gWAvdQ3Ws#>f*D^_tP!)q1~4=3~?b!KhPAHvv&wY|g`(<lJ~00X0P1
4|-T1%LuHmVg0O}ujU9~73D$zv7$#v6?U+gR!b;o!3acz@mmW~MeD)xfR~v|H&kT_$`-
RV3|xDtA_!&MMfO4}TsJ#(pfT_UrE9n*W3VqMTYV+F)TSfsMFyHHI}6Eqsw)tctmv9kCkBK=^!og&DRaR{>_q1Vv{!QS4%MOe^c>
asqQw-?F|a&1KFm|jFKCZOo7`~PUW-7Ud$4xrW@;#?eFY7uEaietLH;7D!}e`^oq#ZT4FB01w5Cewp8q=wFP%(-
=kGwK@x%U8(|T7nt^X-
M>3_ygH2$Xl6+iDk<FAJ>Yy6yEJi~9p`1dgSX%^GQzt{O&Q|LH0`Ju+o`AHV@#=q0}AwSXi2|qLS{!@OE!N2iuK;(eG;U{MQDdnd
L!4x)5=ciWxS^sJOS(orrlb_*MjxHwVBJ&QS>t-
``D;j^zk0?Kn+a*HO@gMoA#(x4sKc$2pYy7Qc>Jh?DECZ&<Chb=6FH9(ZWfHhG_<yi4;YVQh{oynoe}SigS;6ueG5IS?+!N}B5y9
u-o$y1rNDV$uvY9>p0&lLz-ztT)|7HIheol01@k2<5{LC*)M<Dq^%1-
@K9o51Wn0V`!^r!*t7yg5ri^xCm*D_<Xf2;k^z$kESq}Tr(Z|7XgqW?mo{0PD*MK(+VqW9wkWbuIfN3aE)*2EYAfBfo_j37j2*90
Gdi{_`9#2`QFVepb3gfZ=ZfqvB+>;un~$q$A%3`Rirl!nms{#V&dA^$=68XS=T<~>8FJA&B&B7h91+Qp<H1WcX)f{3kC{u*5dLRS
NueSQIJxP<X|t{f|A;}CPW2uG27JjMN8NFVZ-XzNq3<<}yt00q&hN9GY%`2hsw0pJeWa&dj*A{KE)>whkefCx4?lvp{FS41CtW%c
+^5<pJ)F>JE``~DXi1h9@E5D)zj!^nTc6<{X13#c*qasOF1)yQAqW+1UpwL@xUQ;ti*4L~fLbmV`6*ypeKD{94;4Kt7Y4+s%Y1x%
cq+596w2}KVA2m^#Z5?9vW&t@Y5%i-
)t0B|BIlEPtTav4!k0`^;BG+5+3Pws0XBzqM6st8tj1J^A)V;E1l%HKj{Xv(F|(VDL)S~IwDa|ms@Dq{2v;OtjwL6|cpg9%CGoI;
R8q(iX18HBGo8{jPXk`8`v@wbTAnY`wb%o0hL?eF8!z`Qaa(1el@*|`cZg=re%1kDO}hmLX1Uuo#k=K$JP|5LyPJ&q-
D_Vd2Rk8wNvyqCm+1PwY=GD3wyEbG0%sbbNX!H0r(!|_MtLs!ASj}bci&!9Lq`9c3niuKf?mNH2ZqX1C4fBD17QMnbkT}%XkwBG;
}_P-J(%v-!aSomxRN4kREt%KM;SoehJr2o{Cfs;v*f{XWL-Gyi?TsoUC4PAdw(_F}!LcIpEM;8&NXxKw4&?9lpA@UT(-
U3`7O0)Py95K~&JnMi;4N5CGS~jK1pMzZyn~yOG4xv?-
&`w|jtZ^|rSt4h|F(5>)h7&HL9b91li)4g_X;wVo8G=j_T%t@X{~lZq_i>0Bm><(DQZhue`bjADpebxCIFYC_1Il$^=0hxq34r5k
xPuWG*Fcr9o;V`FBf`hY5KSTO6+&B8M*V#{sC6%-
U_<4VIZ*LUqPhz4upvJmOi`I<7%dBlO`tMP>{7hx*CSH1{M(*|4aS>r35d<tm^`hlbX8{{TT7_d#DyJQ31>Tv!5r-
*WwJe#*$%gSIVN|7lCCHbHAJ)Ia+l+EmoQrbXq?IN2$SY1#TN9^r%1BB{3Uj`cnlqr>{~2F5H_)<5alD_^pRy=g8dcw;-
IHi@F`%?4n#YN(TL!vI{AEB6lq|6p*LJ6jLr(L$g=k;dEu3CLoP7zZKw<Iy}yfP3Je@01e;i$?srEdjaU4ZO4M(7ZxT2~dJ1}=c&
5tYkXI;H{D2MU!si-T*9<V`T_|P#qey)R!mmsn?-
<(6{yu&O0MhZKc@jXT*tB#)QLw2Fi%J5@9FufTsJ(!H=6`?;j9WZK)(dtqDhqu#Xf!h_rxYeS-Wnh3v>R<%W$P8*60}~UG1L6HP6
K6#d}+GkvDbe#4p$AHa*C~jCEzKvR5Ykh@F95S$mI13=)ed$!Egz@SEAkl<cT-&ZU1#i?SxOrnpYc{*-
k2maC9k(k}P+WB#c~R|LY-yx3vCvq<3P!x+&Txv3kIPhaB}fK_V3i7s-
Vq)dGd@af}N0w$rI_FY>1f|6f!%>wm`J29Wr=m<7)k4*t$`DF6LjG%c3M=#uc*A3}e>!8~@3>5FA@-
wazJHahby;I!*^(&Mq;iMa>i)wB6;{#}TP9!h~f7v9Ze!jgqY|LM3KIO~6I1{C=5_#`;O$xk639QV)@Wi_+_KV6muKY$)g_DYwg!
H>)&5AKsZ@5F-hKf#X97(ag(CY&L?-
GlUHY2Ea`JWPfM(y%ebhsVVed^lc2CL#VjLWuK|%M#)cs$Dh~BhF;YrYiCvE5(l$;>2HKUx~;p(|%+cV#6?AoWVs2RvZ){*Qlmoa
n=8#2euuP8)sONj>(PpMAs9ybtW<18-
W;SQDR)2=xB^Tu|;a!l#TERyg1x|AjXk;3Qi=K9ZHL%5Z;!e#<8M;=DCNwIO~6x&5GY=J|`~Ab5ZACz>2dG7;#}Yy@z*snxZaBiX
#Jh1(f)YXoXi=Qo>J#OW4O8GUR+REb13~{6DGUzp>#wWR{?k2*zOlsU?1Q@nT#K+=qWje_zafi-
e0@84}cTCH4;FH~5|`c9Hz{W7I#E;Jy#V?@}fCowlJ=_Iu!$5$ao3BH8RWWM0V8uVd7AkFYTF9Y=};^Nn8m%9MO|+;!s2H>@~JG)
{ekFr-i`)kCg={N~RQP+s-0I3kGAs((!GE=hm0ap-T%>QJnKu@fY?Xq$(V;822rhhw{aO)%k@8IQ-
{!r2H^xbF*tn&zsA@RfieiW@aVgUg$cM0l76hq%D!ru;nWf1O5#v*Bboroa#)qbm&~#i7hmYs2ZFJUoI9VnB|kL{yj`e<@-
a?DwU_{vgPYg1RwL3`YJa8RA(_hocx<{vY7A;1&St=wFgDXCqSP7n&o5I%fpV6!7Medl4)|KzXwf$aASobQg*@XG1hZNOQ$^e=Uz
b4r$JO(mb>H3Q^{f>dPEjc*Q7lh2}nI4$e6?XP#E=y$f?5bQ3b;TsdzZYC+|%ldp&}=idMjoc09hMH}6#;>ww1%6r&nC^G6QnR39
qGc14lF9t+qlr4uvFVB`kefrdbE*mN1Fj<~xGDf7!!}^A@<<g@@C(I+7ub4HD_V7rY$GU`*7;DbPBF({siZ$Ptzr69WQ`W)n!ki;
!BCjGiejj8m!<tiK4k#l@m@~<j4?5lfTYlEV3^P7S9?>-lMJ~8OHa<U|U0S8_<Ij^=i2=a6k>-
{8#J1YhccU}pY@mq5wIoAr9B!Pypa24=kp*Jmt9bGKk$G|ct*L&86eGn)-
ssiw;ei7L74VRQq!Qvv!`Df=ZX`ZD!Wf3`Z5SDjY4aVZ@WENnnC}1CM}h|jSG<@9-
<z1I*AYAF!OKCeiT8%7SCm}C_o(?lr@w{GAN5}#7<?bR;Lm>)dtsmdIQm|_;Hm%iyXb?}!Gp-#?!ph%%jo<^@}-6TH}UGQ;CSM-D
gL+c>nE<^`zZboP)h>@6aWAK2mk;8AprK;?k}GV008zZ000yK002mIbZ{?7baZe;X>)L4bYo~PaCyBNU2o*J@!h{dP;iLUtmTipT
-yaUsPEz=4RT3v=Sv?PL*Po>wPLNbCramYHv8JX7HH9@0{snnYS5zSUvU3KgZ_)o3`vQUs6AhjRxrF;ayVa{8O{uMQI#t%ju%bcR
6LHoY_%?{+G9mg)~wFTLhSA7F>zBQS*gFyncxo}=x>)yT;|!l{kmd_e*a38g?`V=<uWUl`fHu7_}&6pNXnw-uWCS{SrE;7U2!4ge
0{Tqb$afkxRJw6mBW%~%__n5<cp@P`2?rFDzl<vKPxZmdacm$oY$9S5!HFLXo`d+jgSeJ)Iwu=Ud;0{xq8Z9G+fksdv5{%3CkslD
0&QQY7HCgdGMTk{_FVB$+Odm{Pz6pqxjkB<EN)*a^TU)r}5L%lV_jdM>lkK`t(UV@bPcX+V_}?WU?3T?S1muhu%zUFIw{Y6L{rS;
D5oBx~!g*MVV*yr4OKcNzR1u<itlH@%x!rvpTtalD*1`sl<z#m}-?okMoQd^)pa5sKNWj`?M@Lki(A-
JVsSaQT1xd^WO3nS)TLM%L=b70Dz?ue$I+Gx#Y=JoC4s~o0nw{t3F`4kQnD=U@#-<%0X~mXXzBM)-
ZTTBgjG04bd1Gq?huACLRc$FG6qsJ;EeK#Rs$(WyPY@>hchnr=TqjfeWKfOrW8xJ^BQ`1};E^ap^B;VTo@JlqxaX_|FBe_D_}o=u
bVx$ib7x&mSEeNB5&&`rC=M5M85e>X}XBOpXRMcxOJle;9U)Iv&|I%gBGgK*C7t#+X;4@j{@}OWzNqWOCPFdx9`@Xt^ogNY4@+Ox
93!wlI~*iqr#3FovQeF9lDhmNt|~J)mH~Vyt9Bn2t;5K21kB%7ipWVE=VY5!q|-
yT1L{a6g8|54F3W#0JghjqTBVy4|lh7+Yb8GuXj`*Kx&P1eVKnXjd4wQwkj2AjG%J-
cVg$@xl>bItV<M;*`~F>ZMsykAcD2!d7B83={GErsl$qbaI|75Ta(cuW&K}h&rEw_Q)V9q8vER)`5TEhn?2c4oW7@QBD-
>0<dhhrWs42T><FaKWRX5RrWQV>OQVr_>VZNc;#(q-
PZ4vSKaimD8n<{(Dbx$%rD4PDtUem4OH$W9o3W8O4a9t_Gi{^(nM{<Onz9nLLdp2CDudVAztb50QM0i5|Gz4!sVdGv^Sf1$A=Hxz
Nl<?<Cj<9MrT#Sx35F@-
pqS&c<4rlQS+Kr1%%1K*XBR<J~})5+`E^03kVYT1pN6E6XnFzUbu_T_Ehch*Bb4v#d61qZpE!rL_bNbHLG?G)04n|j0s&)@1NbQI
dJa#!<E2;&(`ZaOUNb<aIbyLC6fBCJmC@tPnb%!=1PD#;sWd&dXE(1kMIl=0b&>;;I9(ChU||3KZeBaeV&vlKdq_~ob(HpH}XBat
0{r1Ds~NDkX~n3nvNZQ6&Zb?t7t3<qEB#}>WHN&|MV6tgJf>%-K${3xGk$`OZ|ww;E-
Kn&QL(YLD3p*(u}<n1IgIbfOYud`Hu@m36Ad8j|xj@rszB4!DGw^oWbJI;}G+0hSjc}(g)_&?mbEQyulqY6**Pgq5NO%3PnmjI8L
400`kRB&15fmOz~Z94d6?9DLHLVw_A2Xr<v=cn@UVG3QY8B<#>|JSQ3}c;V(|H3R9V9!B%Md3{EMDzZWoev(hc|k{l1U)C(j}zRD
5tNf@NJsckTl6SRfbvH?;_47OO#7_w$J7&d^GG)t;b<FBskK%#I)L$yc-Q2uHSiamtAq1-FNe_(p=c@KA-BT_@7Nt{b{N-
0u#FIk?!kpi@7Uq=xQIDKv6XFkemCFKFc?wz*S1<D!jHMj`9+LZ=AeGeR}t~H9zi8L3omT@qlA|`eu77z$7y}qf;%R0u@z2KyCTm
Qq;GdvUz*g89?m-
_(TTiigVj<yI0f)*Kwx!HzN=^8+ut&z+c!!~{Vm2I~eVokI=&V^4)g!Ebl<Yr+Y!mfv#V`EcoEs_9+1`;~9P=Xk(xl4&Na+SIYV2
ai7Np6^>Qal4tDa8V_b%AQ~yIgkRTCvC~QOBcea@U%i?OKwmCBElJl-Dn^yoU3T3I*?cAp;8`z6jg>@~BA0mH3jSdjmn0;gr=X#v
U6n5YQxSc6p5@{(uMP8k#hMp{!d~lPzc+Bpi*|a_<7WDHfPk6&mOZevRP{HPR^w`$AxfS;FmcJmWyod<Cuw`Cr9~B@d2!tjuFLZd
Z8TXTXLT6Auo&BMOuXhqWwOrKAN|r<#<JxMaugJ{*S0h5wRD;(c=G{g=nzY+z5e-)t0Vcr#jhTR-
9jCVRa+BZNfwRhlhPJK_2C{_(|tA3STZ{yNxb?x6U3{h`utI4EyQ%Hk#D-
IPSTW52mcleUyUI>tz!<c)yPHtU*mmN1yIAOZK818CxvShh}%kdfd;3hpfggI!eOx(|ZU^cx?{uv)}A#l<f%m`gyEmK0CLx-
766WJq@CrbjfXG|--nt7Xa^W5Nxt-J4OPRuJkxD{QX<QrWr%`B{}*2DPhR&=169S~V^{KAjU0aI~z-W*zJhj^|iZ-Tsx`etY}(^7
e03P5~o2R8Y|RvN?X3&h^x84lIwAaRsyw+{E3?Zb|PJXZnxab!A?WN)&ghQ|an8;y?m_<%Cd)f~%AoNBKXK?GA+lKGwl~CevRd80
dHixtv|xsc|YLtTe%;!$Gnv#*^iVMq!IX(5mNe_W4aYMw2bTsM5W1UbC#Q8uw)IoheRtk?p{CRK-
L37&z&|qDNTltgan$l;dKk<VpKGcxjhM$r^j$bh4V$fs3kbUB|f#xB-eOt<HHdyN7ueyaXDZEOFHrS=bs;M}|<$)>;rshT62okc(
jhPX|cr{>vFBA!S-
w;OcJ70`8*+E~p39(NdA}s7th{WH*>0nT!;K2unmA4^A`&iyBEk)i(G7#o&lWZ<`F}Jvo?yj?!YCXEhFpz!5_*v`>9P2k;2yjx%_
TnHA0OFu&qA6D;u>^afln2?l_5;vEg6E5OItB!JJZ!06?i`T?{6NyrCQFs>cE{*hEbqK#7;|Ms8j+wcDMyW8(>|G`E|QeUDRoBjU
xzy1D?-
;T{LtENat5#N9C?%^on>z!niOI9tpV|F{%3^c46G&!cf)>QAJy=0APzzBzkX>9J_fBwsV{`7~j*_1WB8k_w2{c*H4zjn=ysKoF}R
7lV9VH9u31KZvFecz5J8mvWzKx_EI3cLw(UrwP77fTWNFO7&vEqJ6glOGepKf`~a5v-
GPwQg!2<F6o8oK_8!kua?YBYXsBfStq}C5J9J{H9*)|H2Pjyu%5*)@c!1#fiZ(<P6#3W{l&BC$eS1@SeDn06U0o5m0_s@mSGOH_N
6{6!OqOY;x0e%Oo$|Wgbz+Td<Dupoo}1e1I76jG~1)%0+&7estjmeFy5%neY9~3-<9G)Z?Ld&wJqPa~L-
R@|Q4CQ{{p!cnoV(x&&ykv~^+_sTre~*xjMh7X;fud$+r(AGwWhubg|o#&F<ohg=Iljd(H9>6?-
myRkLsH4nN^j;qNYZOEbT(k_!dcV8LBjQ(5H5RbZG-
$@Uols8whp$1=NQ^y>kEX^9sL_Ej^WeVCSrXm!~$d&4h>Nk$?Y2d)lO;{Rmg7$J+R}<sQ=ZA-fM~jDS?mZ$_r`|>q-
}+r1q>`5buuaakeOOGKjoh<pw%)<sh7xK+A6px%ohrAMJe9YcCa&QxJY*smugbK^Ay2YQcjCQ(W9df4tUOy~wf@b}{X-
aF#Zq2Nfwx1oLTkx$@=Vm{-R1g8adUAo{h<~wZ>aHd-hbgwB}>>pM0R|lAJBV9O~qmfWB9RsV^1JW*q+e4CLjLnM%{(uee}_=eo;
l3t>dY;1P2CqdC!AgZ>f=rQ}?^q2!2CtDdrsUVYe#W>BSrBXV~u=rt-oWk<Yt>gsLbopn*HKK?7czyhhtTzZgiKiL8L2RzOV$a1%
P+dffo@)PUmJ5F9Co62wG4$ZF2Jt}x59uesXYU=>msvXYHgC5cUErI@;K-Z7?`NE-PQB<X|YHQis5C(&htb#M<Z8Q;)etV`J)CLv
A1F1MszD25L<^h?oz*oCMAXZP&wx5KR-
m)(taxQENMDMRUf1+7bQR}D=(yO6i@tDpGP_3U=<9o@|T{Ih5OcctRf{tRfgksVp}`v}+1AC-WpKJpo?l3GtJudtE(Ur<W}1QY-
O00;m803iSX00002000000000G0000;baZepUtei%X>?y-E^v7R08mQ-
0u%!j000080000X07Lcq=E?&A0N4xw02}}S00000000000Hgr`0000&b!lv5WpYqqXJs!zZggo@X>xUQP+@0fE^v8JO928D0~7!N
00;m803iSc$+hH^0ssIi2LJ#a00000000000001_0R#j9077+XY-
D9}P+@0fFGOi`V|8<LX>V>&VP|D7aCuNm0Rj{Q6aWAK2mk;8Apk&LHn9H#004~(000^Q0000000000005)`(*^(lLUn0uWMy(tVP
|D8Np5p=VQg$rVP|D7aCuNm0Rj{Q6aWAK2mk;8Apl7$XM1K0004G0000*N0000000000005)`3JU-LLUn0uWMy(tVP|D8O<`$nP+
@0fE^v8JO928D0~7!N00;m803iSX00002000000000N00000000000001_0i_oJ077+XY-
D9}P+@0fFJE72ZfSI1UoLQYP)h*<6ay3h000O8001EXJiHOYVF~~M#5w=~9{>OV0000000000qygL)002UDbaZcSFGFE$Y+_+!Ye
IE&bZ>4*VQyq>WpXZXc~DCM0u%!j000080000X09BFE&5Hs60Fnm)02}}S00000000000HgtWA^-qFb#!!ZZZAo0aCLM-
b#!!ZZb)HnWNc+}E^v8JO928D0~7!N00;m803iTtN>ay#1pol@5C8xl00000000000001_0Y4=G077+ibZ>4iNp5p=VQg$rVR>wC
VPr^QZe(m_axQRrP)h*<6ay3h000O8001EX000000ssI2000005&!@I0000000000qyYgd002UDbaZcSFJE72ZfSI1UoLQYP)h*<
6ay3h000O8001EXNLYSpixvO?Q&9i_2mk;80000000000qyaN4002X8ZgX@laCuNm0Rj{Q6aWAK2mk;8AprK;?k}GV008zZ000yK
0000000000005)`<Us%cNOW{?FGzHBa71ZyaA9;~XfAMhP)h*<6ay3h000O8001EX000000ssI2000005C8xG0000000000qye=~
002mIbZ{?UUukY>bYEXCaCuNm1qJ{B000aC3;;m`008Aq00000
"""

def __cubkit_bootstrap__():
    # CubKit import-debug: this function is generated by CubKit.
    # It prepares bundled files before the real MCUB module code below runs.
    import base64
    import hashlib
    import os
    import sys
    import types
    import zipfile
    from pathlib import Path

    # CubKit import-debug: decode the embedded base85 zip payload.
    data = base64.b85decode("".join(__cubkit_bundle_b85__.split()).encode("ascii"))
    digest = hashlib.sha256(data).hexdigest()
    # CubKit import-debug: fail fast if the embedded payload was corrupted.
    if digest != __cubkit_bundle_sha256__:
        raise RuntimeError("CubKit embedded bundle checksum mismatch")

    # CubKit import-debug: cache extraction avoids rewriting helper files on every import.
    cache_root = Path(os.environ.get("CUBKIT_CACHE_DIR", Path.home() / ".cache" / "cubkit"))
    bundle_dir = cache_root / __cubkit_module_id__ / digest
    marker = bundle_dir / ".cubkit-extracted"
    if not marker.exists():
        bundle_dir.mkdir(parents=True, exist_ok=True)
        archive_path = bundle_dir / "bundle.zip"
        archive_path.write_bytes(data)
        with zipfile.ZipFile(archive_path) as archive:
            archive.extractall(bundle_dir)
        marker.write_text(digest, encoding="utf-8")

    # CubKit import-debug: expose extracted top-level files for normal absolute imports.
    bundle_path = str(bundle_dir)
    if bundle_path not in sys.path:
        sys.path.insert(0, bundle_path)

    # CubKit import-debug: build private package search paths for `from .utils import ...`.
    relative_import_paths = [bundle_path]
    for package_dir in reversed(__cubkit_package_dirs__):
        package_path = bundle_dir / package_dir
        if package_path.is_dir():
            relative_import_paths.insert(0, str(package_path))

    # CubKit import-debug: mark the generated main module as package-like.
    # This prevents accidental imports from global MCUB packages named `utils`, `lib`, etc.
    module_globals = globals()
    module_globals["__path__"] = relative_import_paths
    module_globals["__package__"] = module_globals.get("__name__", __cubkit_module_id__)
    module_spec = module_globals.get("__spec__")
    if module_spec is not None:
        module_spec.submodule_search_locations = relative_import_paths

    # CubKit import-debug: expose vendored libraries through `from cubkit.lib import name`.
    lib_path = bundle_dir / __cubkit_lib_dir__
    if lib_path.is_dir():
        lib_path_str = str(lib_path)
        if lib_path_str not in sys.path:
            sys.path.insert(0, lib_path_str)

        cubkit_pkg = sys.modules.get("cubkit")
        if cubkit_pkg is None:
            cubkit_pkg = types.ModuleType("cubkit")
            sys.modules["cubkit"] = cubkit_pkg
        if not hasattr(cubkit_pkg, "__path__"):
            cubkit_pkg.__path__ = []

        lib_pkg = sys.modules.get("cubkit.lib")
        if lib_pkg is None:
            lib_pkg = types.ModuleType("cubkit.lib")
            sys.modules["cubkit.lib"] = lib_pkg
        lib_pkg.__path__ = [lib_path_str]
        lib_pkg.__package__ = "cubkit"
        setattr(cubkit_pkg, "lib", lib_pkg)

__cubkit_bootstrap__()
del __cubkit_bootstrap__

# ---- CubKit entrypoint: VectorMain.py ----
# ‼️‼️‼️‼️ THE MODULE IS A PORT WITH HEROKU ‼️‼️‼️‼️
# ====================================================================================================================
# Repo MCUB - https://github.com/hairpin01/repo-MCUB-fork
# MCUB - https://github.com/hairpin01/MCUB-fork
# ====================================================================================================================
#   ██████╗  ██████╗ ██╗   ██╗███╗   ███╗ ██████╗ ██████╗ ██╗   ██╗██╗     ███████╗███████╗
#  ██╔════╝ ██╔═══██╗╚██╗ ██╔╝████╗ ████║██╔═══██╗██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
#  ██║  ███╗██║   ██║ ╚████╔╝ ██╔████╔██║██║   ██║██║  ██║██║   ██║██║     █████╗  ███████╗
#  ██║   ██║██║   ██║  ╚██╔╝  ██║╚██╔╝██║██║   ██║██║  ██║██║   ██║██║     ██╔══╝  ╚════██║
#  ╚██████╔╝╚██████╔╝   ██║   ██║ ╚═╝ ██║╚██████╔╝██████╔╝╚██████╔╝███████╗███████╗███████║
#   ╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝
#
#   OFFICIAL USERNAMES: @goymodules | @samsepi0l_ovf
#   MODULE: Vector (PORT FOR MCUB @Hairpin00)
#
#   THIS MODULE IS LICENSED UNDER GNU AGPLv3, PROTECTED AGAINST UNAUTHORIZED COPYING/RESALE,
#   AND ITS ORIGINAL AUTHORSHIP BELONGS TO @samsepi0l_ovf.
#   ALL OFFICIAL UPDATES, RELEASE NOTES, AND PATCHES ARE PUBLISHED IN THE TELEGRAM CHANNEL @goymodules.
# ====================================================================================================================


import logging
from typing import Any
from urllib.parse import quote

from telethon import Button

# api
from core.lib.loader.module_base import ModuleBase, command
from core.lib.loader.module_config import (
    Boolean,
    ConfigValue,
    Integer,
    ModuleConfig,
)
from core.lib.types import Event

# local
from .Const import (
    LOADING_BANNER,
)
from .Button.CallbackButtonHandler import VectorCallbackButtonHandlerMixin
from .Button.InputButtonHandler import VectorInputButtonHandlerMixin
from .Button.InstallPayloadHandler import VectorInstallPayloadHandlerMixin
from .Http.HttpDispatch import VectorHttpDispatchMixin
from .BuilderPage.AntiVirusPage import VectorAntiVirusPageMixin
from .BuilderPage.DiscussionPage import VectorDiscussionPageMixin
from .BuilderPage.InstallPage import VectorInstallPageMixin
from .BuilderPage.MainPage import VectorMainPageMixin

LOG = logging.getLogger("VectorMonolith")
LOG.setLevel(logging.DEBUG)

class Vector(
    VectorHttpDispatchMixin,
    VectorInstallPageMixin,
    VectorMainPageMixin,
    VectorDiscussionPageMixin,
    VectorAntiVirusPageMixin,
    VectorInputButtonHandlerMixin,
    VectorInstallPayloadHandlerMixin,
    VectorCallbackButtonHandlerMixin,
    ModuleBase,
):
    name = "Vector"
    version = "2.4.2"
    author = "@samsepi0l_ovf"
    description = {
        "en": "Vector module registry browser.\nhttps://www.0xvector.lol",
        "ru": "Бpayзep peecтpa мoдyлeй Vector.\nhttps://www.0xvector.lol",
    }
    dependencies = ["aiohttp"]
    banner_url = "https://raw.githubusercontent.com/sepiol026-wq/GoyModules/refs/heads/main/assets/vector.png"

    config = ModuleConfig(
        ConfigValue(
            "limit",
            30,
            description="Search output limits.",
            validator=Integer(min=1, max=100),
        ),
        ConfigValue(
            "max_batch",
            50,
            description="Max modules per batch install.",
            validator=Integer(min=1, max=100),
        ),
        ConfigValue(
            "VectorInstall",
            True,
            description="Enable Vector Install",
            validator=Boolean(),
        ),
    )
    from .Const import (
        ICONS,
        _ierrs,
        strings_i18n,
    )

    strings: dict[str, dict[str, str]] = strings_i18n
    _cached_groups: dict[str, list[dict[str, Any]]] = {}


    @command(
        "vector",
        doc_en="<query> \u2014 search modules in Vector.",
        doc_ru="<\u0437\u0430\u043f\u0440\u043e\u0441> \u2014 \u043f\u043e\u0438\u0441\u043a \u043c\u043e\u0434\u0443\u043b\u0435\u0439 \u0432 Vector.",
    )
    async def vectorcmd(self, event: Event) -> None:
        q = event.text.split(maxsplit=1)
        q = q[1].strip() if len(q) > 1 else ""
        LOG.info("vectorcmd: query=%r", q)
        if not q:
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_err_empty', p='<code>.</code>')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        if len(q) > 120:
            await event.edit(
                f"{self.ICONS['warn']} <b>{self.strings('v_err_len')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return

        success, form_msg = await self.subinline.form(
            event.chat_id,
            f"{self.ICONS['search']} <b>{self.strings('v_sending')}</b>",
            buttons=[
                [
                    self.Button.inline(
                        "\u2800",
                        self.cb_vector_search,
                        data=self._cb_data("v_search", q=q),
                    )
                ]
            ],
            media=LOADING_BANNER,
            ttl=300,
        )
        if success and form_msg:
            await form_msg.click(0)
        else:
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_err_api')}</b>",
                parse_mode="html",
                link_preview=False,
            )

    @command(
        "vecupdate",
        doc_en="[-f|--force] \u2014 update Vector module.",
        doc_ru="[-f|--force] \u2014 \u043e\u0431\u043d\u043e\u0432\u0438\u0442\u044c \u043c\u043e\u0434\u0443\u043b\u044c Vector.",
    )
    async def vecupdate(self, event: Event) -> None:
        args = event.text.split(maxsplit=1)
        args_str = args[1].strip() if len(args) > 1 else ""
        force = "-f" in args_str or "--force" in args_str
        LOG.info("vecupdate: force=%s", force)
        dl_url = "https://raw.githubusercontent.com/hairpin01/repo-MCUB-fork/refs/heads/main/Vector-MCUB-repo.py"
        if force:
            await event.edit(
                f"{self.ICONS['search']} <b>{self.strings('v_upd_req')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            res, _ = await self._safe_install("Vector", dl_url, notify=False)
            if res == -1:
                await event.edit(
                    f"{self.ICONS['error']} <b>{self.strings('v_upd_err')}</b>",
                    parse_mode="html",
                    link_preview=False,
                )
            elif res == 1:
                await event.edit(
                    f"{self.ICONS['safe']} <b>{self.strings('v_upd_ok')}</b>",
                    parse_mode="html",
                    link_preview=False,
                )
            else:
                await event.edit(
                    f"{self.ICONS['error']} <b>{self.strings('v_upd_err')}</b>",
                    parse_mode="html",
                    link_preview=False,
                )
            return
        await self.subinline.form(
            event.chat_id,
            f"{self.ICONS['safe']} {self.strings('v_upd_same')}",
            buttons=[
                [
                    self.Button.inline(
                        self.strings["v_upd_force_btn"],
                        self.force_update,
                        data=self._cb_data("force_upd", url=dl_url),
                    )
                ]
            ],
            parse_mode="html",
        )


    @command(
        "vecme",
        doc_en="\u2014 open Vector as Telegram Mini App.",
        doc_ru="\u2014 \u043e\u0442\u043a\u0440\u044b\u0442\u044c Vector \u043a\u0430\u043a Telegram Mini App.",
    )
    async def vecmecmd(self, event: Event) -> None:
        bot_info = await self._net_req("GET", "/api/tg-bot")
        bot_uname = (bot_info or {}).get("username", "").strip().lstrip("@")
        if not bot_uname:
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_err_api')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        link = f"https://t.me/{bot_uname}/vector"
        text = f"{self.ICONS['shield']} <b>Vector Mini App</b>\n\nOpen Vector in Telegram Mini App"
        await self.subinline.form(
            event.chat_id,
            text,
            buttons=[[Button.url("\U0001f680 Open", link)]],
            parse_mode="html",
        )

    @command(
        "vecdl",
        doc_en="<slug or URL> \u2014 download and install entire module collection from Vector.",
        doc_ru="<slug \u0438\u043b\u0438 \u0441\u0441\u044b\u043b\u043a\u0430> \u2014 \u0441\u043a\u0430\u0447\u0430\u0442\u044c \u0438 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044e \u0438\u0437 Vector.",
    )
    async def vecdlcmd(self, event: Event) -> None:
        args = event.text.split(maxsplit=1)
        raw_arg = args[1].strip() if len(args) > 1 else ""
        slug = (
            raw_arg.split("/collections/")[-1].split("/")[0].split("?")[0]
            if "/collections/" in raw_arg
            else raw_arg
        )
        LOG.info("vecdl: slug=%r", slug)
        if not slug:
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_vecdl_usage', p='<code>.</code>')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        token = await self._get_active_token()
        if not token:
            await event.edit(
                self.bannote
                or f"{self.ICONS['error']} <b>{self.strings('v_err_api')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        raw = await self._net_req(
            "GET", f"/api/collections/{quote(slug, safe='')}", token=token
        )
        if not raw or not raw.get("ok"):
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_dlcoll_not_found')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        col = raw["collection"]
        modules = [
            entry["module"]
            for entry in (col.get("modules") or [])
            if entry.get("module")
        ]
        if not modules:
            await event.edit(
                f"{self.ICONS['warn']} <b>{self.strings('v_dlcoll_empty')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        await event.edit(
            f"{self.ICONS['search']} <b>{self.strings('v_sending')}</b>",
            parse_mode="html",
            link_preview=False,
        )
        max_batch = int(self.config["max_batch"])
        total_orig = len(modules)
        if total_orig > max_batch:
            modules = modules[:max_batch]
        col_name = col.get("name", slug)
        await self._safe_edit(
            event,
            f"{self.ICONS['modules_list']} {self.strings('v_dlcoll_hdr', name=_esc(col_name))}\n{self.strings('v_dlcoll_count', count=len(modules))}",
            [
                [
                    self.Button.inline(
                        self.strings["v_btn_dl"],
                        self.cb_vecdl_install,
                        data=self._cb_data(
                            "vecdl_install",
                            modules=modules,
                            col_name=col_name,
                            total_orig=total_orig,
                            max_batch=max_batch,
                        ),
                    )
                ]
            ],
        )


