# name: Vector
# version: 2.4.4
# scop: inline
# CubKit build info:
# CubKit source sha256: 83817d1def5cab763de5e053d9b4413b16cc239467c609632a0780963aa82b6c
# CubKit payload sha256: 7e3ef97c1e6c5c33fd9a8a7dd9b69a987f507666e577e7e9d62ae86f2c5bfe50
# CubKit source map:
# - generated line 488 -> VectorMain.py:1
# - bundled files are extracted from the CubKit payload at import time:
#   - BuilderPage/AntiVirusPage.py -> AntiVirusPage.py:1 (lines: 98, sha256: 265539ad410b51022894ec9867e0363cd591001082c8fb228542b980d20eeb00)
#   - BuilderPage/DiscussionPage.py -> DiscussionPage.py:1 (lines: 47, sha256: 3e0713bcccf3dc931dc4dad661d810d96f616427725503f71cf0ebfe3b8d0d77)
#   - BuilderPage/InstallPage.py -> InstallPage.py:1 (lines: 79, sha256: 84b9894bdabc5233e66014363732744b419e98405a1b577259bb995267fd497a)
#   - BuilderPage/MainPage.py -> MainPage.py:1 (lines: 386, sha256: 6ca168e90178664fc397a5be6b0d4c38043c6c682ad15ce7d696565ed548e9ec)
#   - BuilderPage/__init__.py -> __init__.py:1 (lines: 0, sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
#   - Button/CallbackButtonHandler.py -> CallbackButtonHandler.py:1 (lines: 591, sha256: 5311ee8d98babb39ca27c7ef00e4f804f6c7617833db8fd4646a182633d37749)
#   - Button/InputButtonHandler.py -> InputButtonHandler.py:1 (lines: 54, sha256: 471685eacb1e765ad3f2b1f86edebd1a7a85bff6b71014788b1389edae4e60e4)
#   - Button/InstallPayloadHandler.py -> InstallPayloadHandler.py:1 (lines: 194, sha256: 69cd46e19a50379baf5dc93ec555e1b4ef9311733acd6e1583e60178c76b280e)
#   - Button/__init__.py -> __init__.py:1 (lines: 0, sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
#   - Const.py -> Const.py:1 (lines: 422, sha256: 7dd3aebf44d3afceafd3469d8541726e8e6c117a650a5299e14397df5019af64)
#   - Http/HttpDispatch.py -> HttpDispatch.py:1 (lines: 435, sha256: 5fcbdffb82b02a78abcbc56acbb9d3272b33fbdcf7cc60e413e432e00f690160)
#   - Http/__init__.py -> __init__.py:1 (lines: 0, sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)

from __future__ import annotations
# Generated by CubKit. Do not edit this header by hand.
# CubKit repository: https://github.com/hairpin01/CubKit
# CubKit build notes:
# - Metadata comments above were generated/normalized from cubkit.toml and entrypoint code.
# - Bundled helper files are stored below as a base85-encoded zip payload.
# - On import, CubKit verifies the payload SHA256 and extracts it into CUBKIT_CACHE_DIR or ~/.cache/cubkit.
# - CubKit import-debug comments below explain sys.path/package wiring for private relative imports.
# - Vendored libraries declared in [libs] are exposed as `cubkit.lib.<name>`.
__cubkit_module_id__ = 'vector'
__cubkit_package_dirs__ = ('Button', 'Http', 'BuilderPage')
__cubkit_lib_dir__ = '_cubkit_lib'
__cubkit_bundle_sha256__ = '7e3ef97c1e6c5c33fd9a8a7dd9b69a987f507666e577e7e9d62ae86f2c5bfe50'
__cubkit_bundle_b85__ = """
P)h>@6aWAK2mk;8Api*$4=;8E0021;000~S002UDX>4R=a!_GsWiLT)bZJ&;a&>c1VP|D7aCyB~OK;ma5Wf3Y5ZZ$*K<i|)HzP`s
7JKMny9K)F#W4h0q8v69>5!D0BJ2O&8B&t<Y!I|q9TIE!aUS0choeHPlB8)-*-
EoCCA>T+Z3&f9S!%hGX0iB<2$fN>C=gp|A^2`}pxUqo{a7i>7JhxTdIy_qvvm9MefswH(_b-
3naLK5MJA{*<TJ~x(znv`&s<mLBi*yV`4gAx1%W4L1xa@m7kO$}mfqV^EDaMyOt@v`n&dpQF*(q0Lebp6lK;pDC0Rs%zahqIuLmD
VOGXm6akXc58K5ADN$@6!S`aS?#M^3Y<@jg@)JReU&*;MH{kwlYeA<NOo->h$+Y`Co-8^G#OH>@4t}k{sck)hpG`Pa$-
YmmoN~=7T;9?k^g4Te^s08n7!`{K{o@Ea~M3ipiEj(wIa$#TxZuIb41|dD4&Jh{RUIxH=*<-
zQ06jA880;#oW!{Uk*xqYKZ7SH23BMLp@<FPv@*EN?)fb+Y^Z*K<drSs~7A#nk4v${6jr+JpXCL~NYB_?IRPc<e$_&6vYo$l%Omm
2zikHBr_Ltz2A>W&xA}EG7Ovg;kSKL(_qQl`f@+C4=4&o@F8rH<uPpxBB9S%${BVS5qUbpAm^1Ukom&`h`d@m^;VKYqGaAmXYRz0
ffmpf8~@fuQ~9>S%!hu~TxWFJ7^Kwpw{INkR2VDPDVl_uN*^b8bnS*TYk!Yu<WE{`h;)XIEW1kL#zo#x3rp*2iYr(@LoVeozaM#e
^~zJLhndEiQL(g84@q8VQ)g2^Smb(=`@L?cPd7jD_C|J;s!ogfEAch%M9)fIT-2oABgg>g-
Hs4IbQ;hPYubWDm*{V$=#AE6mm++xd$xB5z6{HFhn8DGo4gc(#d%ZyuWnekSC%#5kZlIm~0OQ4q39i`iCx(h+jYbbtcJ%9Md$rzr
-+0gJTs>*hHCM+&%lM!U`@^U*2b9BkO)<I?NUtV<g?A_=tPwf-
>(n&K8LUeeaJK?Y`cZAQUu8VHLV>Bx%cO5Yz+&F)6#`!63oq9L6@R>V_6&5PEwVj+D3R_`a;xSk+x$Q!npgjTC7yM=}9rauV4hE|
)ip!;oBw9>OfDgM)Y~x9gui<3D|Gie#VGT~1W*&^m;~M9|nA}s7>PoK3PATDZxmgjh{b4aCFnTaOH#5c^u>%fg$-
RKBc<h`v5$4qWB22)<{6~v}nDA2D4(qdVv_~6&XLG!nY#1)LZ!2q+TycrqPB)eoTi3xRIHo%*T`hnc!x3t<E!(A7)#+Z%19NI=;?
OC;@onB0e1ckIQ0F3Xe`A-P#OH`79P%xay?_)akF)BcX|Kjt!gi)i=a?U}-
enxVlBPqPqB>LgXa;T`m^7PDsMAHMa=2g2#k2e1TGp)K2%Ut`h#I+P=qxs>(izn63m4;=fuD{3NA)&Ezz)85X5w#ZOw!{tV4}9*x
E_O1iNu6G9iZ>CJo#5wY@#q;rlamzz{=t~P)h>@6aWAK2mk;8Apix*wd9ln001fn0012T002UDX>4R=a!_GsWiLc&b7OULb7^mGP
+@0fE^v9ZR85bYFc7`-D=haAkWxxlJ)tF)+Fo1r(q59tGGG#KV9a8(-71^^-mziBN3yFPS`G-
0=RME7XQpUWMHnku(>8)JBCA?8hHwC7xRDC9=e;4N%6RD&Ha84EW6(S&GNCii^Rkj_O@4~ZsOF2*S*tZ-zw@2=Djy}p9>FIU1z~9
`%bexs9JV)A>AQXVXi*kRl5@jjlFQ7HC-O~!SQ6lsh>14Ml88#(N%u_>LN`C6D0*Lf;2Cu+0eQQ!d-
0i576iNLNY6q0Gy=N@QqZHLJdxXUb+i?Ph?lU_{^EfdULM#!Zx;Q*iF<biCANLveg(nl_FcN#zy_`}h^AQtCwe}=R@!K+-
&Pgwgz>41(156B6s&~SsA3;qZ|6-
p(Eso1IzGodZ0hBvqe;u91YuiVPs;s=b<*XW`L(kDG8@_o56@H!CMgB@PVwLZPDks(r2<W>iG<Flb$k<Tr)Kfi?3KO8b?0}t?%eJ
}trmTNexwty5szko+SLS@DKG;17!AX4hSnpj#EWKlRZj@;8j2o0g*qogUe^M0zo6DQ=LKr#cOCSO#AMj8^#xXfXp8Cv6GFVr^J{$
V9Jx9gjl^;_!%q_FXcLJC)5wb4MDfeOiU0J0RSIWfrm6~6#6NIg?SC=40UF*Z3BIEVyjRBDA<gGgPW=MW^fPTV-f*-
@FiWy4`;U9KF$}j-YBO}v${c-kr87`X#r9n9ndL*pj_!=p)6uTSqW2w4f5r8M0UhnAjYibvZziE`4fbe^0v`(qme-
M=Tt+Ct>f>MJob!6k*Qj}FfTh`iZZ9d%=~>FG2G=v}>`c14G0(1iYO^USn@B5bvMW*4<o-(4v(R?*OaB2-
O9KQH000080000X06<<gu>S)90F4U(02%-Q077+XY-D9}P+@0fFG+55bYX04P+@0fE^v9JR@-jlHV}Q+R}d-|rU0*+-
A5q~P%MIN&`naf#rDB91X>!|tSQo<s3b<<fA5f#Y~2iOQ9jrbhjTkKXQ)D}lB8)-
n_5Gf5?&sZHiSv33^QEGDhQfAp|)Etw?Xg|K4we=h1HGYFL=nbis{2Qg-5<Ue<h1nBi@3+-7RPueuvB`{ivi8-
0Z?A2!c$osv=(SfToxbzq2ho@;5G%fZ$@)QD!8Ef}|BIAm#oPbwax;5XGF7Dz62kl9iB<%IG=CMOtgoykJJWI3{GHl)&Kr)HOH*5
&3vWOnnfr;?m5C;FVeBJTvQca`u1;#atGOhP@CH@}VLQhYwZQi=cHLolO{hyx6mg@0iR5Xbi@|Mx#k_Tp@h$0)n=9{`Jf9>EY>X|
F~AlOkzGh7PCD6)f=a+m;R|ytPbTm%b=<-
&1#FD*em14K_BlyOAv7bN@@YIxl<2850_|U_A0cEzXd{!9v2SbZVY2n8nBHep(BA^^wXTI)?+1yb<tX$6oaUM(3`o>Hgz3~z0`)9
g4Rk`XDnk4nbLU`jh*#(3NBH70%}(!4W)X4>xF{13=W3eyFa8V@`OO&mc`ZuHv$)0Eo@<pzzz!2Ao<Z@7C4dP-
?h{SRBQl9Jek^_#D-it!TLhHGuu{<r1;aNowtt7wpyR}3Z<=m!sXdbpErfwkA<a-
ROFTnXfsATQ_^tRjDvRhCbyQ5N{`qXIFklkvXNkfsW~2y?+0cK^1#OB+k~U68hb0zY;zW=&2+Y-
lg*5Ilw)mQ3B$OZVP(A4sy@(9QH;Rx1C5+kj77qPa(MHd8-~}KzKxzN79>P0A;pf<ubLYOr+xSQ7vcLQgj0Ne`5c|5U4j@o-
GNs7IxV^U?+yvgYOO(<gmhg;SA4r(irL`+GN<pM4IxZA1q{6#-185(quDFIVtG!}b7P}{?Rydn_&AY4Pu^YT^!;-
AyqwPbO2A<)_foyeup2RkxJo|X+^nwz-SF9)?C`lL&5+8?W!k+*y(F0=t79=fU2?!=@vd!^rp5}E(NW~#%k$G8tC>4FTc617=FSU
jH_L5BXD?~)0-
Hsr+n+agm&yt*!3~B!Bm0Io*jpg4S#I;jQlz_F&+rogQ(pMYhyK=`2?r7#<E`8o2hAw3<e$oW4@Xo%$;wx8J)BtffEyeje{eq8qx
K@FsM>GNGh3X$rbYT5vFt8|3m|sN(IUK{QlM7)j>b=6G>jJ2$5BpxGuY)y)wc1VLa$7_`n;pb7(pzVp+4e;|BHt1?P_j5`WqbYE!
uPPorxOUbM*g$7`mJ0^AB0G*x_XId35bIEC~OWVf>Hck~(uy@GnqH0|XQR000O8001EXT(oMnuM7YHZ8rb_7XSbNLUn0uWMy(tVP
|D8O<`$nP+@0fE^v9xTkDV8HWL5tze1;=SgY~5-bGRzj5>WRl0$Ln1L)&EIEElgl&xBp6g~EFKL77GGkl1YD6f;-
Y^xw%i5w1xzZni^#&TTdd&l?Vrfy2+`%bbi^0Ib<EX(VlPV%f8jYQivsJ3acmXB$^*(BLUJ~mkr<`Ij6IvB;sG|aP_-PJHcGOe1T
C|OnU{`$Uv;j-`B?4CC_WeP*4MNn2ucD`@&nvF)!V9qc|Io))64Z_uG{LkO}-
+lYb>xtvDDjbd8{`600A!VFySp61mSvhupXJMU}Kjc}SCiT|!Mx#-
f236&Vjv&c?4mRwE<SxnPqmcvGHx)t=?peLfBWj6Q?D$z;?tKKs&w@Q0-vnvH=1x_Yp7Zxt_;*gUcu^n7qk%NV;X#`GhmGAI-
~8*^o!}78#mP&@bv>^)eymzl>$GG=8ic^*U2`>?t$_~=HRw7d;lm`+10*qv;|@uCS2D1rOq$EI+6GrIzvK&>vJBTh_Pptq-
9^cURrT0g&M&`QjapzMR)a45G{`o7)x>dfH?CM3+h8q|Age1t=HRjnB`O>I{G-6nW`~~<!_SQ6aZ=-
5o$TtIdQ!%yrMYd~qhgBF0z*^=&N_t~Frf-<XzXGq4uQ#F4cJwTy=j`?f@$>-AWlgv{${PXECt&}9wXD5$Q=BA9yKYW$tO-
3+|HdS32RzC-n7dH8=ppO-E78gZ}{9nqg;Gexx|A@k4-53*Sc-V_2OD>(6^Mdqch&yGe$(-
XwViu7HWA&38ujjN@KSPT*Yg#Ag%H)Y_Zv2xR1~xmMhf~!+r`;5QRjT@Ap9#Rj!A7ZMm9vMNg^(yi1UQy@wO70Fy?{1c+5(4-
7>>v&AkF`3D`pV`s7QLP@!ZI0noMeehYd!$hvz>*>=XYSW-
7SQgpWa<I1I#qDY?g`p=;lMYz(XV;w!Gtt*OSJ0jqkW_w>rAdZUuk$<|i|N{S&pSPw{Mj~7BUbi#=$%81jwgVP*o|-
_%IctrrFnr25f0TJG;p$rM)#ZFvR#(n>Pk=YI0jxMpfRK300c>x1Zl?z^hsbzXHea+GKmuwon~|fRn1biDTDnvv{Ei#1L&M}Sn1n
4G{mk7TH|be0UrN;+u`;VKye2{ucAhYCRbNDc>+z_+6M0IL({_uURFN?eg2N!1LIid*!3p8F>u~e07RTgAi>Ey;p)V|36EmHK}uH
gsO$Scv1&orJpxUqAsq$&F*lS8c+)0S=v8@BhRo;f9KJ^Ar85)^tl~~Xx8kaW{p%_G>y8q8ZjSr3(`9<1z87jw5Asu0Z#X(ph;$N
$6ic+f$fH9jqSH{b5RFotMBb{4jNG(y@&ldTG}+NCNmjRfc_T5Ld0pv}$~s21+lQ?oBQO;tTDpXFu&H!1dKPQzkO~z;#BWhNw)UJ
r>>gyGfBb?6I@K2kN)OaZE_BPem^c^0Y%V-7>mX)}iwo~42azRe&3tUvR-*K;E#&cJo&rf&89-
1M<_!d&V@y7@kg{%ylr6y&oc}sM<{3=X-fLkI*#_)$X(n)s6lRD89tqMXR+5z)u;8SVUJJ*PL)0~-
wjb|?dm*80(t5bRYGALH_d0>si}oPdH6lK_km1M=D3YvUMh9Y$?s&k<_tHdcP>#KNyw;zL2SI3=5rYXO7x(A8eiR35xq+3?f>1ww
K6usTy}bi3sb2IBH};s4-G!{Eo$>FO)4eXs9Dw@uzTmeO+2vKhL2K<?mn_)zu#9$nL&B@|RsE<;^-
0KwDXt$Nc&Ohx!&#b(K8@zIz4_-
V57RXgL|YF<6H3C93pE+aWE#g!6bCJHUN=b^`P+J*ikvyA*`9kixR37Wpqn^#UI!`N_X`Q!!}5?|;)v*>m(?NPULrjiAQAD!X(Ab
?bg9gsQp6&tRy9(OQOrV&3{C(mR#e6y6}L<<(3lwPv`B<{6+an&7@Sm4GI8Dnkc@jHMPCGEE%I;G_RQI`01_!@4RK<tTG5E1?Sbk
K-(Uaq<1fn#ej;3~j?PzDE_!vqnjRg4-
tnt1sL5I18=V|()on!DQlDsn^8RlN85f%NCq#OVGC5;D!wsK83{`V@Zo5D{d7H||f@jZc^ePgl9FrEvU?5*d*%Z1|(y);>84+7-
LrjXPZXZLLc3rFnrs-jg2`gWzwi@rKt&)S|lM-P@iIwBN%Ut-Q$)m$h8_#*=T-
uNp%%0mSD9E<g_}p$RIBiwqG7bia7dL(pY}f^Pf(85+j$lEbUMF$#Oe>c4kl6i-#H4Tx9B2WS6s%LQJ$(^i7cJE**VD~k-
^S)10D$yP@{;YdJ@2A&lCU*Wm}SIrel?q|%p<^9R1ewVRqAkSQ(4hYvN(qz^<8#QQg(nDKpZV|{;}eIq>NbXzI<^~JoSi)47xQ;=
ipvde<@Uf28>l&2T5rUIa1Vccg)JzA3$m@99pD$(Ya6m$de3>Q1f@lO*uPV1mw1yUtWCz)#LuItbpRAT<KEu(>m97hCGw{+d}r3*
kEB0Jxr&>i`NZ=@E|mg%b<JKizulGEcpUTFIWBO<J{se34@1nXvPEsb=WY%gTYeUr6J-
QpJ`R33G{>G^Om!fl@TIiFH)Y0>9hXVN8L*q*nyi^2uIyfowuSb>bgvuc+p7;I)YA4Hax>XNShj<$m;JS;qlEHBGp#PPYj5Cwhu?
7>rC}aMGVt+B7HqvW+|6OWEVpu&>w7-
=6;0`;L^Tx<c^o_3m^K+CL=I+E><xIHtrQ|T;Yxf_t_Pl$F#UBAVwd0o7CH}`~1|pdIGl?UU@@b{G0*EHi;la$6_nX#?p&HGGmT2
hEVOtYUwdJnVuhq8GMi)qNS4U7kFy%IXz(%LV{P$OniqqbeQAy7)Op+rS;Ik(knl7!fiReoO%45ROoxh11<l_!;iCs{*ch)8BgUb
fn!m1Bg4Xn*-iuwQ73Gmk~A_}&j0aA!bOo--do|oiDk4%lK%;@;&}poh`vP00*`U70+P<tY8K(z#}cI|SZo2hl$G@I$i(^l^WAMw
ZYs++{_<NDck9mOsCK}yR}|T;H85zd)_mF`N!!LtCF*%o=1nnoFtd`?Vb%AZOWUf141h)adsHw$stdIJxG7jx!{M-
@Suj51y|hl8qg#)m;<!<E(CaRGHG;k*;_Zq@r(k68k=5CmSp-pKMd)ZjNQK8GG$@>>JMIB5Tdf1w7?T=CvFw>58Q6DCT|=rC=Ec4
7lF1Ts{&k)C*x{}w&U?%E&N>4g>Da><8{a5(SAC9(8my9z&os3Yp~)`ziz3p12hTEBaB_tn7xX#ducdJPCW~YO@GdqftaS0-
%E|)31DG^rdOjfN2odPk2()i@w8;D+Av&m@R{JTf!Lj_?Y&N@$U%ZH%1DWG-
;H?R%vNEXIBj^j+z><RyvyugEktf&PnaD8bAouE%f-~4JK@(D)pw#gkBx-RUBtiTKJGov4yFp*}&W9DI*|}EURW1>u<&CA*SCs6=
PcRNmAY8rloX>#FpvWLplN8Ub6yRP5&-
ea*!|Pnj!VBMfd>PL0)y7$TLVwb(vfyTz=tE44CI@aV?kSFwzOg3iU|q<Yi4ztJ?KmAy4bRrHTG^Rsb?ekvVs%A{71bw;tef=28(
0!bJo+CIOJwKv9MoSEN3y#0mw&R=@xAx-Xqojb&xoX~Tm9pYRr}eWQc^2dC{kM935^ehN_D>3q>pj9a7HI>7E2KF;bUF5dh!g<tp
fKa^tLv2fWO!cL9WIi>_GR3n}DYM|Kc3Hp2pWotST0s0~L_@;g*Gui5E`&lyD6?36Tqfq4Kt%y3azM{Nk%pK8uoiDEVbK;Kk<nqm
#A`zqRP(v}@8(Wn{qO#V3u3-
h;!0fkxZND8n`1b?Cjwu@mq4FR2CqlCAJp4dx5Ruv?`_J)Cy8OILKdI8@yC#<$X1S;Pr=A{ws<4La)!D8X%z)Ev|)!H!r?9Qq9p{
vLrXTzowP>;_DI=VO$Uu-gT%5K#G|^X5N)Mdda9p>IVi$5PH_;sxLOzF=eKO?`Ta*Y|sbux`6myZ>fuj9q>Jse{-1qP};r97c?-
127pBW3B<3HvzyEoiT<cxDIGFzvlVdJlmWYHBejL-A;?V7;_y>$e`@CWUNuEUt5h8j3-
LgJq@080w1j2VL#AU>fkpQWsp=YR%h4<{yye5C^PV!W4Cn*bLTTG7Im;YA2S`RAgl1FKiznkm8HLF60A}MDJ$#6uVn-
C{SQz}0|XQR000O8001EX000000ssI2000007XSbNLUn0uWMy(tVP|D8Utei%X>?y-E^v7R08mQ<1QY-
O00;m803iT%VCa{e4FCW`Q2+oR0000&b#!!ZZZAV&Y;0m-V{1ZnbaZcSNMUYdY-MsTaCz-
qYjWGj5&o}JppbG2h$xD3$&SM^wDEeqjw`ag6>sGa%|d~|keVe3KzQg8MOAx){7Y_-BcyU3Um#aV_dEa$Fd!+3vSmm3VH5N0>Hhj
LJp)bCcwxBiw8)E;xUNALNu1_}7e#UI<us16tu0xWT|_>O<!czvW;B|~*PJfM))Ytc<0vQRc}OR6w5&*ylw=vN&o2__C+l8B7reM
gL+H{^yfh=S@}!7!vbFUa!%L_fJSBZ>7sg&d(*7b2ijcSyuj=G`VL0*pd7}eNOETH!O%&3Iyak%P8Ji%Cp&Ref@4tj)=d!7_Wx(^
|r#J5RFFw5Lu{W1wKL7ROi=(6OU%dPiRK9!n>d(CJ=>3Zy-
n@G)%C_vSt)us^4M(!9KO^}O{3NMm{)PB?oW6~tIHdWp2~D^B(91G|SG*K!`M${WIQpX(1tCe_(sLROx7bvFkgK(9_RfT41Y~MV<
J2c^kpx~&_!{uZNI2~o<dj7DP~}3;fR^6S2&kWrvOMjfXvW6hjCXNFfO!0m4PzU-hwN=wj!LHn;DrxR7UGi<z*SThoxvJQG+3|Be
Uc!?Y_*ej=Fyzf*!QCB4ESW<Vh9q@+)`@snVOf#i~gIJ@85kGZD+(w{p0QNmGOLX$ZLQHAgs*VK1D9NDLL7;ub%Hs4$WR`G=^Fiz
(^ePIA4UCCcx^s3sj#{a_0Q#g&9%XR7-
@F^$ZtS&R4;RaWij9Tne}Zc}v)sTxN(T%LM&_chj_cC<{8h;FD~gbL|oxKY`q3+>GavncC3+P(Y>OIL5xVp1{hQQ<5}|(`9o)gU(
6qJCf-NCG{unDe;4_l<c>osN6Dx3~Lw_Wq{MsxN7Ogp&NM%qBNC-
i0SXls&Ni}DRkqM&Xnd=F?1NzsPN9gIpqGaN{1|k#!qUkTMF0K0Jd6H$_*TfMY<u)a)e_Gi$MsB3*F-&-3DESH9F`|EV*LazWNw-
b@JmP%Ap(k-w8=%iRoA`*{@~Px`qSLr8y`?1KXn((%U5xq<!w2`jlZ*ZyfM3KNgP%kDmg^Sua3-
P%IV~9L)~rITpg3WwNT8)ay^XbgYz&tF=^3<2e9eP`*w*8j@gWpo~z5#!x$|h5_G+_%&!GVXOil6c)@a^l2{_+H;I$ae)pvh|eO7
Rj`9*L3|>mN9vt*HwLW9P~>V)(6)EU;v@^!VadU^#b7WyL6~h9(L92eZ5#XpLfhE}vCE!SHw56ejWa=gy(J&dY?wD?<x+{u1?lt`
ALihgxz3h(IX+-daJ$Q`;Zt)L!#3CE#!l0Zp#NyM1d?0~U4bZ5@T=`9U@lI2yMJR0-fT1&3ljwaC~`xN+?Fp1tA*@pR?-
+>(P{Hk^36qXyTB}W3PvK(&ZArXiqSy|P^%e@>r&rK5)uV^{a427wh*ORVk@9IS(tSL$?*WFOo^Apkt2y+(@Ll%9Ccz()6YUe66<
l*1O$O517h}?iEX;ftO$`)9idN`%?-
dKqsc7?V`7Kd4voQjGn{#8v}y(y!k3(SVPmGI;Jc<MgQ=x+M9rm$;dXGmj}Zo9@f@s7or#SA43;j8v5qbn$V9hh8aw#I?Eeze$l@
JF!)N1`8Niu%wGI4y)<(HXA@@nf&SkyduJP;&j95w(Dr<qqVHH+%QOyRAp3`<DD)?890LGaO?Nk%=aD1n1fh?mnmfb8$;k11oKmW
V^ryq+c8BEvn_I?;=WE0+gt!NuIPA-p(?mF7uKoq@hz<#2{w<mlj*c|0V9b!H5nk4Esh4@@&KZdsZU~mB7KXJCd>)u%7v&KdYpH-
VNe423x<6*T~U@<%D<D5h;3mNOWmKIS9IE?o_n0rBU4r@P-rgSzkS&=!0Ixm_D#0Mk?{JB`-
X2o<$&ugM?iA$1kw^C!2O<2N@XdCdT^IDSi68dFDTH_=aszI}ca^3|mzdAmZWk>H{gJqw_V2m3^a%emXg!9PQ#^}U(gqbJi(;06e
B0Fh;msi~{c1wf9qRA8cesJFR{A1$I$ps6-PF+qpgjVUoJ@&F=7W4wOSMDW^atrh9ef-
C=>w%Z>s5n;O&eFI@vQarQ?rym}>QX`hYPw<E^rR7p#$kXvf;i1dpzG6zNira4G~7KHsQwudGslfIjM0{}Zmc9uta*=Vt6i}PcLU
`zMzu+977g+ClY)kUi{iC#{GPF|;M(r)GoJ*a%b-{KjgsMwj@XbpX0)>eHc@C)wMPdWFRSC2Jf6+MJJ0KX#sG#Y0Sr~Mc*~<3a-
MimKoFvnI1a6<rL2JtJZn&OVqlZo+y(-
%?}?hDgk=nj=MIqhoFRm@Z16!qlvR!BSi_^GC}m4&BUMUQgH{T=B7s;=k0y()2QBS!GJ6=jNG>_@hh~^Igs-
3JW;+0@8>yQG;A(mz@AMl|pjCiw=}!aT%k=L?8s;ZzLO)T*Tt}letTj?IZ>Bj~|6dNNt)=>6u6o+4wv@EZS}Ln==EsW#uqJbpnd5
6_)Qm0{w1%>y8ZplYOv2OvOU4QPra;vB5dH(Vh_<7tK1^5Ot&+D$9%B-
_GBzxO%)BKgky$*K)O5ou@?)rL_Tt4$`iT@L#E*<l1jAL|xWw76jLC&@$wyEUTc~WjqllgGw~YvXdce;kv0yZOx<BrxVnWPXefsr
ZW{qDQPmF5{s2JN+WfsR1D&uNMI~n4-
tM_Ea8D17(F3F{hLW!6mQ)S>nEox;_QRDU*HmUTaVj;^`C14*hhrjU7Ezl<mTJIPKwz0QoJh5wpK@<4rQN35Say)|q(;Ef6)o+a_
5K_^|vfu?IWAl<(SPclAYaiIq;2h)36gJm*79s~-
>ZF5n)lI{|or&z*r^dKNX=w~l!Ih*#*~_lnXLUEy<kmXd;sfe+3RZ?XjDlI{%tG8A)k6XXj?O_k2ws)5tA+Krb#fU#P};jFZ9PgN
;8fLcr@LX72;1UYS9Ip5fByR4|NOmU2Ph?jRCL?)b;V-
hFd!2!*n%}EAFjw9B9cG!qFBr5ugi(%nUEkB;Nx(isJUz=m=27nY2i&0X@2_0zrTRE1VHavT$Lu-cL@2qphqC+NglZqe{OcfIV-K
xwRkG6(q`GXl8eH{12fmyJD?H&hBgn&H`v$RD{p)&A(p|TB4r()E2X&l0OLz%x((b)={Hq8JgsiOFgJ?H#ESU|-
kYL4ZmR`(G!IGpaJYHHNtbU0d9WK!&GX)yrRx|W-
PyP@oUW1@%n~opZLE_cK>Pln=bbsR4y|m=$_@E4t5CKOKO~OD>rKEsuy1K}zH;zO?|EAdNbk}8anDD^P=LgX5Xd2&*Dnz)_}#Z&b
uX>z#A;*~tSXlG)#@kby@t+k;Py7BMeLNfancOUTwK^Gaana+(^>H*T%j-}-C><L8pd2oGyE4vn8-
vgBx&yaoEGiP;_~CK3Tti#0W61GeeEpC!7!smmb$uv1|{dY=l$g@SBA62UCUz95L-
o@B8mt^k&=@(gUp}afB0GB&8Oxb@MI6yQNNf8l<96>mMGQK@Y|2I3XXMMq`{Wv)Yqxa*zq-
1mo958=geus3>$;sEt;{*g^^Dzc6k#;VH;phu!Yd6xoP7mJ2#`MSk}Tg`(TAZsCBDLgZ3}Alv`=pS_-sWUn0B+TY(%lohfjU-wV%
hMasgtEyBeuJ-
7l6g}7kkQ(LL<k!j%(GqahAN6Jyy8YNhFlz?Wnfz(}G*Ew4I_M&Kc*;Y<w%7?=CxAjGMfMMw++ATPFL*xv=W}s<Nu3?A^?`S0MVd
I7F;nLgN*RcfRGPXM1)h)w}H4hnap(CssuXjFPJ8E2cEUvq`pSh<V=AcXM1RV$c0qcEvC5?FwYF{(uHx8)v`I4H#P9Yvzm<V-
2mSdPHS;VIhLGr+qH}Zl&cXU%J`Snjv@7WhZ58>5)4zJ{E`Ju{&El)j~xc;Xc3cEYLci5<(mESI`bhB-
`?wBkLHLgRI?$eWozf}ExXFBLo^^sQ^+jzT!_vs=pKS|+amoVV3H@U5HqpK+;xvc==GoWm>WzUH3f)#_x2itzV1QZ9pic9VFt5qt
Y#zq?T=(R$|N@48AWzI4>2f?xeM!WcWsV)rB8foG`#Z4K+g1OPFFkN3~YraqMiojiv#Ww%yr23{*XeENR79DcBwb}1xua4ViOiON
~)%Y}bN%zC+-^jr)^#Ju9?~?q4`TA8eH6hXxw{iW%FH)Lc>~efIa+E9q(a1b>?ZFx4$9bOk#-
U>z3<h@y^`)1>5$m<T3UDtlTw__e<<VLM#l(!byvBT^w85QVL*LWZf&Q8-VtM!Gf|@(X<vYSPJgM(R?ks-rqhF~XmA}4K^SzP3FR
}bj)u2gB(%9GAw42+r^^!H~`X^29{7X0}RzVjeE^=r8@u0(V)!Y?q2oE0r{tn%h{It7Ew0|XOd|%zwgNOgW_VCv>8ms+z?u8GV;%
hqdfM&kNbz*UmW#Ig*#!9NLh=Ot=F7K)v#|XZ+JM#P39sOG0PBi9cFsfyz${2&i5BtC{omt*&&P%UFTyYp%dbq}(2GI7_{{T=+0|
XQR000O8001EXRguxnivj=uk_P|)8~^|SLUnX>Z*DJ1Zg6#ULUnX>Z*E9oZe(m_axQRrtyN2l+b|Hm`&SIQ#4c{w_Ef@Vp@o+A(4
I;!%OVteoQTMhkmNjQ``;_cjvsj}TUbE?n&&s)%*d5dHBeeLt}#d{@LDV5fJvzwb6iQABvr5}lyrD-
g0D_Cw$a+4wXNPAHJ9s??xQ>=Nm2-
AE&Rg5Df3P0#(ip>Q}Qd5r9ktYAGlm33HVcD1+?V0Xsq=~sX;A{lm{QWicYCTQRUF^ask$vY!Us!G3c>N2>N-OU>+UQ-Xff+_KqH
;eIz@&a+2<iBTxCI8TAORgP9s@!3x|cQKDIn<EK8pccRR0Nj7yUnPW?Dmij`@RMs5@E{Qh0X68r+Wj5ld;<6lLbIh#Kos$D^AHX$
Q;G@6gLG(26<*i@|9R^Sa2+1OHoo2leufR`0j5q<=kxfYMf4!#iQPxH^8hF<TTCie+C5=)$-
!ajkO|xmR;8v?LI7PduHXN^|9o`sKDpS)9vl}W|jp>Dbj7olcw|SstruGueEQi@F`}=1Q2j@;oE@EUC5>G}CWO>QS88@daBqonUW
%(ctxm)4+1b3uHF|$Wmv@K`S?$L~!-
i~+MbKIeHi?DDxgawTQki(lCnBOsfT`46ze_xoe7zg8rk~kEw=Wf%la{BpDpbl$))+x4U+_kypEuJ(a>yj+ve|CZV<{CYZeKN*Vv
@wRSCT4$Tb_L2b+GcPM@2}O;&eJV!BeEQ>Ep^Rh=x1B_Pt#y_WkGIWd4P8x?(SX}4m-R6PA`iynL`-DeyMJ}DdB}We-EO2;5}SIk
XNk*jrp%yw!VaMO0BFLB}_-f=I!VV0bc@jlD)-
!^P6(2L2XGO%VR^oa4@NC%2li~lDZwg_5T1+O9KQH000080000X0C~YC@Yx3d07xDH03QGV077+ibZ>4iNp5p=VQg$rVR>wCVPr^
QZe(m_axQRr#TjdF<2LfUe}#@kQK_dW&OVBRQ5W4S(sY6CZm^I0ve*i=MA>R&%1cstAm{&nGknN;I!X>j`5~sr;mmN}oMfWhdU2d
psuC=Yy?nbXh4LuprJ^b?xtz`H+J?$ak+15{Elu3KDA((puid9$Zl>}rn`KBNDY;^|3J^FNvfAwglhW*0qJX_<M}=e#;%ikZHZ%K
*6-;eP9;qVADxPTGBAO&+#g#j7!PMJQ<=Nc_rW7zF-
?Oh3lPdH+?NX}P;AS7cy4x}7aK7fd%3{4_OoV0ur)_Mr**6~D<?gnEMR=d0q$v~8woI#n#VdNa+znO9hKUY*i}d+5;|lQ>WkL%B8
AZRq#p@gUGY`hA%h&P0Uwt?a&DW=ozr`QUe|dlY(JZ`q_4XpZeEs&K`S}h%gW2rOy9;mWG#IU!dIM7?eDWWbs8al1^0LU)h5+a+D
X5g5*?0|H(4x4ccX-F&C{GI}e$Q`nzL;q;KieDnf&QfOjwfEqGVfZSk8^_{-Wd$B1J}?vBrCGeV<?1$l?5&b-
pNni+mf?I4Vh;iFiw>cz6K9HQdWwD-mkQfEI0t-
5DaXcH_w8tYhn=?X_l`)lhzH%m&xZ>Do@+MO5C*<aIA8kl^}F_LvwpF=1j$cef7!3`A1-
!oPsT#s`bgLR3zwQs5sp+K;au)rSR_e0cy`Dm1F{U5eo?-sYJf>gQzeQ^78;XxP!si=hZ1f-
wg;lIX8GuiX3E)#AEo))tzsU1;9X_0vq!-
MRuF89ay*i0XOawZ4x{=Yl`}?^W)N+A61NO@$2kDG7b(IYrfEk0+ijnMFP%&HG4T%KFkB}AImZAT8i}=MmSVTmng0`>2>!7y@@Rh
s0<+*nyayM9dF_tgdQM*$PRa<*DQ?<KzHv3ytfXvel7KmS6HmWYRxg^Ipu1mqhv#2J#A~Y&0!~U`nbHrKS9TN>NC02zSMT^>30~A
MDITSSdQ=;j0C|GsrShZI@FPDG<?8mXxU&g9EFq?<#Hrd`P)jd81iObET4V<{qr;L#5)Uy@%4j6(6IMzbOU`FA6OoePG3sX<%y$j
lIX+n7S7T&8<$thPD3vv_jTgi-<zPDG6j)7E+}8evdXgj)(`e%q8y%b3&T^2wFdM1C_53%N)%lJr3wLo3MG-QPrkW!iE}{)NOmI=
jvbx`pD?&~kkx&%fROVd=u#{g_cgQ*elJJSH<#kjD{nZ2R#WSQ9@RBk=qVXPd<!A2t~tdr6Ijs5TgRaci7=J<#FhuP99XolF29u)
FU-g=#rAD9MCjQ9%w^5qg_?+*Z2k)b&IXeuY(aWx9qNHGs60H##{7x{T!+^-
)}H*$MYQ69%ssKC5~hbDztWjK&83@GI+~FEBsE!kYBGcQ2G=ZA`(@PTzG~$?h6vQOSydEU)TA%S=RX!-{z+Q82-
?)5T&DRNWIxfOn*|i(5}z>m;)t=-
WNF92wC!V3H?;afUrAr*d{d8=H+}%6riV`OllQ}X8b`WPcb*CKAnG(ly<glLDZ@m`PN*?wn{I+{tcbIlzP&bT{D|?SOc|J(%1-
`8pz3Nd(ciWYxkzs4vzI@#Eiu}#TTlTeqMm?IPnx5o+=2tM*aCL=Zg~2*8k<XxO|P9G+O~-
Lm7$YF##p+d$yHx~;83cP3;2cTAQ+WUhvElFoq&z5OnN*lwZ+tbg1C{b;@Z%fmNZbPWGqJ9zM<}_KEZYcO_&MI#5>f1pBK;O^Do1
AD*Y5NJWoLMasUr7KFMs2;9#O}iVON8Zc+{8Pk;oIIBL&0j@tBry+;|e*4C&|<M=y@kx{S=^SU$I#nW}5cR=QQGPSCEvKZ=@>*%G
(<+~3bM;OujjkoTpO?4+u2uIHS30@OJ>Z8m1Q5cQCDMr#RD8{ktlSa^FVZ+4((8iGwTB~CmdOyAewV9ythGE-
CF7L@LO65ed1Og{uZurO%B$x!tN-bZGX}_Hq%PYn^?FfAJp}Ac{M#b&nY@oNsUqMF$Fb=Y!oU?R9$K;bVZ$b;zZnfwZB{O9f1UA3
9I`WnwJ0`Z2gC`D9oLY_BDhXaVby?PzKw89=C`=%A&AI)lF*$j9uN#}bEltr_mfw9B?A>~!K5FjDvJwgFM^|vz(2JQ6rH~yhYCE)
Cw$T~}L;Lz(nm*YiMUwJLYXZok5YCJSh^9Z#T6$23wtDT$5crLcG|GlGY`SNe2`NtAtGkmtZAra;GSuRQQ`(xB`tJnmu*O((X$x8
RZF+Gas|O-zOSDFakgaWDjtH}|;^}~3M}+Gnhj9@k*Jj6tzz~~-
gQx8K$RRMN4$Z{DGg_d%L&jRo=Ao^nKaYuWya{<+U^&00MV{KXg@=4RPG*xlw!ZGL*ZvhQ`#1S(YrWE)RKuVC2TlCv4LqaJQEbmy
R;vLE(Ilri?^umsJy}4AaDv8Q4;%#pI(TG6bp_P`-9{{EZw}@`yePJe^(8k-
?GpWNe=$D`y%+Q6126MIO}T8?%Y0!obxn$~4_N|o3%`dbHDVT7&cP7-UA{?OTO9vqc|BfLKB<R_V|pJI$Ai7pqo;8+nys$y-
)vH2w67uh|123A_)m&vo4cWa2hVCX&yU}Eq<qp_BL(IE08mQ<1QY-
O00;m803iSX00002000000000I0000&b#!!ZZZBV7X>MtBUtcb8c>@4YO9KQH000080000X0L~Q+nfw?40Gn3;00;m807GwXb963
ndA(fQavR5)zUNbPkgAAWiy#1=K(3+`P1B~blBgBwb?sU%)Ns%MCjw^1GXs%`q$)@8vE*25tx8TMsi+d)?AGSOq-
c|(Nb41PUcnce+N<41*zfP284TtC0ur-wg#f0z|33Z4??cdVtTwCF8Xd3W@LG)-ZQF7@rkSSYX`W%3?$}uH%;Dj?mep(;W^-
(8>Dr~*>r3k^?5C`-
<$1QdI5oAsy<IHr+~T@tImMRMDvbU7osHUc>f`XDZnbTr#mAij@BaMVrOAKMCVyF)T&PXH_u7r(;LnALv8A^+R%`1k%hy*nXv$ms
CMKzEamTvZskvNp^sTm4@3gpk#j0<1*ST$2tx{!fa{K+a3~#HmSr~hB>GI{*mzMtl>%Mw*<$8SOj<#KF%5EK(JGy0h-
1KP0Q*KPq)LT~fikf7~;SG0ci)(dvs;wF3l;*nJbEmNRnbJ(rHk*a9%WF$-T)O(!-
*h^)^I*OuOm+=3(o{dbRcmQxvt}E;rnSDN#ljd?hU-
~cU%Q&Rr7?zoPGS6Ki{gnb4*gHWp*Yd*T<4l=nRovBuOI*Q(e9nMoQ_$)bA5Vdwq)LUM>Q>PX-
<<*EZ%VcZoK%~MBzM1z4X@Awd*U((3i0ZIqSyC^(z^gf$5fQOB~(V;7<F_fBoUfe?R`WJ8x(m?%bK5#*+=c-
Od#~F?Mz1T5WZ0ePbPR#|xg(hU}KrsW)1hng&DE<ECXbThSxivRXycvx}C~EGRK6*VdL-Yj3Pv-
dKXLN~Kg?s8*|`(%9+-S~o6TS&7XQH-Pkn@z&V96JujzdJ7lH-r<|J*5p@s-
OyIrw%1*89LpJB+0nU8hB&b(Z^K4kjH&Ymt8rH!_xO&t$Xw5vV3QZ=Rdq8O3>M5}t9&4DlEcbPRw#_cK8;7s7%at2L{Ewiw_BRd#
|uB9J^Vy#+kaokYQ7+wTV8hSMcLZSZar5xN3HL7teny3<meyoROZ9>-
l5elUACIzfj=s)YG%E~o#3S85!DRS@M^Vjm$w=dy_0Y|Hh0D+icx!SV(N*>b<3%{i>zh1-n*fE%ynHhyoU>a_r0-
b8s0WMIRz;rby#GnG4g({S|(r2oT{kVHaF|z>Lcy&((>BX^+i@UbnjhU&3U>Xn)tRHUr<J0SY+oec+E-
PwtitS`FGN&|FkeWGc!LkyD(RpnXSw$%$M<B;o^<AOQlk|F<asnrou57&z)EDIH_B%xan$jzB*f-
t}M*XmCAF~g$l%VD)TdXhNx}LF>@tVtL6DpWqx|DIx{_6E>BnHrKCBnbfeSYrACIlIuzY8q!r|eohy~9rG-+ZTrOA33zg}GY9-
q5Oue2V6xP><zT~fSe!enSnq8P)C{35==ci}Xj^`E@GFM2K$4$MPe}a|S`RU4B8BT;YUYV)(7Rcu^WU5G(D{rAPGhZn!l&jSWj<P
yiDGepht&vI(xSi<*+)cSOSDM3Bm#cF<wb3gXQr#_sxAISMp)xmLovxBHPS4@PTse|A$IDsrv_}4(=jZ39=Vwc$=}NT(sq+g}rG=
&0EJ;XU+(FliLt7xFDZ@TW)3M{zwG46OptM}|n}*)aR%d5t7G`D;BBrOO<;teZTCP^#;*QZU_<*y6z0J>6W^sbm*;1u6uXejRn{O
$k)W{+RY`Z##f0fx%8E@xHrJ2~awJcjEH%v-hkiB4Fo707$X%lG|A7JQN1{6+}bzv<_t5c$KW-iU`=sI`v4`U>CGR%f`cHYNCAUG
Rm>*`3>2OZn!CJ2c&>*g6*AqhildF9RC9jh6T6UJn(W4E}9i%7DrX`aU&^F0}u<;3HKhUIJ;bvR{}BKGpjsDZV)w`J9DxUY@hSVt
;3F>yW^>+ttGhQpODC5GFE%_4tqa5rOkEF2^Tw++|DW%UGfGltumeiNx+YG$|Vdc4iT=8TcZ9eB-
xXW4cPk0-}_4%`j%EEe@(G$53dA+OPB+q{{S6P%9Ag63X-!)zI5YTl^7YG#N;yf-LHhYCR<*EY<+#n8WONvpDJxZ?9D2K0{O;JO&
L<|0vGM(li)v}l#cjB5=GRZDWA+nOuWX4#0<;&{x4(L`xnM@QRo<9BRro8+;QGTzkiDo;7=!GcImW8WKt%0dC$no+Kry=+eU(c8V
FpxTVQE{`8Y!PMI1H46VEtLu2nty-O<qT6gy^HK+D?JTC-
F*mip!Ea?WS`D2VtwzJp4Xu^#&@qE9^d_rQ;35l`@S2#w)0*Um3mbS%H0kZSY<k;;Qm58syK2QfdrNeIO2{skjm>1!mQg3^)cP8`
4RgNBwv^%1oW*o!$ja#4g5+XyQn$8MmxuYL)Rjvx%;fa&Ry9tQ9Ccf_xo$MN?0uB6U0k(&S3xA~0+n1B(<5g}Gc@k16_gaPHry$@
{r=r_-
<DLL!atI1h7V0|3;K_Rqb^aph_sXGD9V!?q0yRcNUf2<5}wH<FR|HWO3T<fcVJVAahve!uoOd=`uM}|AF&IY7lQ$s613T}^qah1y
fC$S@rH?J1sg2VXLdn{54eb9rbl-
#Ov#V37Zv?|ec;&JVUPYrG&XBmU0&~XjrJMD`$nhL>i#Iz)oBMk$^Ystlux{#=(XvYHQlni(P5^W>n)|>$Szw6^{4Wk8sEKb)OYS
q-
S&_$w(h={HAP)^T(>$74zOS2TPpMx6zBsdBxf4DI}B1GHe8s5?pQ;*qC{UPMNMx==dvzKNM?0ByW=TsN$N*i+reFX`c^pRinbH@G
nb);X0kC{Wn!?_@vK_Mu7_i<LSbM6ZO*h!Od7~x=z;5V+4z=*YQk(zZfY*CPb4)C2j_C>fByH$@Baj~gvU3$E?Y;2k({?4TIVv3n
k{weh6mFj_jxznHL&_+%QT_Dq#ZDrNc_^ZOT}VpWA&QtSaLDf@XA$CUs~T_p2K;nKdoKP)RA_&?rDyfv+g#RYI+%Q19#pac-AHHx
K3Tuw|K@%TDPQ5ZfwDtJa(Di;;nQis)pp;lrG}l-
q29Zq<Z02WTy^l<D~XWDMsMN9i!PqpzZI0)*1?RDPkF~hMtTN)FVI#3h&^RB4N5m7)P#32jixf5oFKQfyw+AN7dzCk!@%<p-
5%AH0HJ}FXOaKtLE)^fopZuMp={NOvs019WQUFLxDW_RD4>L@j)|a`LJ_oI2n5NOXMgrc)<+2Od};!Mn>6Ri)YUk*l~DGu5`ZS%q
g45aNf<1q3j-RvZ3i5(E@>zQVb>$oeWLnJGQc-M<;A$$0iUY!$q}%KF4g?f<v)gp6&&kzp1)C{0n=-aP^MV)MV&y-3-
m~woK>mQm~NfS`V#~9Dc?yLVlEOw%Z+(%+cYu48HAV^ff!ua;{mfha%y&j<}q>71^&88B3kcRYvF{dz~|Hi?fE|xZaO4Mg{k>Y;{
_7nIr1TU68Nvq_9+qU<aO@R+MtX)EvmXj--~mUf`}XE^Jema(?*BNB?v9fW40NKiy~BkxKf*AAUo9Xi9cnmhP!pHTR~P6|J;-
oBFolV-UWIH_XapxmwCj7HG6<%6Z<lgK9nH>!=fD@N~$?Z0LwR3zmkAG--~qtG1)EH?j-
9qjO$QodNaJO<ii_vS#YMl|H9nIW=VtDzcFg1UU&Jj7DK4wOkkGqN-
=<bF+5TrlN{)5G0?}4;^4Lp@uPPW<fK9n<h1Kk#}WDiQzM$7&$zAK43h>(I8U2O#!pFxzvKGt5UsS_bS2;Od)7YppQ~K&(0oXG~e
P%A(!b5t%CwL>d{W6RGG`@FRx7biQoMvQ#Y8b9Ay50TWp4|BFJP2NY4)4;TT$Htyk>Jl)S&dUkp>pI`_~yJDKbg*H{0O39Fjl4Gv
{=fqejR;Ytbx7+qon5|FwFz`)Js%dap29jG9m1s9AgIY0>lPZt9Y*f=@TD8ro?AR_=4;xb}j0vqp`+AZ|cHd}m<m>9x92>_f;2qi
FRZ)I+F<jwW4gdiWu#|{Q)M~Eem^5)_P`Qtn0O%t7^@v65f_z$H8WTI{WEFdobv(;fJjY3b<qSQP>Rf;Td4w~8B*1A7Shi#GuW7I
iCr3g1JHx{rbH8xqgAk}DvMvwU^+n_WY^XH`o!5Ha(WmXY+Vp*4Dc6KS}4yFiP3t1p}n6R9Y$+jL%54V~-
bv;NxA#5pMLQk~^3W6y+9)T%J;JVf3J&BPv1hNK8GJESnb{h)W<_;fXEy~b5Re&f6Hn;+r@XAU(b6^B=^j}|?T;)#KXFL64BNQ$@
_!ieu?{?gv+NKi=u$A7)L-
8>#P<{!u)LZO=+v+qK!r|N3FJH_wg<xG#(W^4PXi*4rEU4<kvpvtyncc>pyS;Ka5%^IjXtrJR3{TQ|g*7;Rau8S0z?N(~yZfe9??
$~tWW{9~+u$wUbhLIfp8fE_BXzx|$EfC>M9ehI^EgELb%AX{kIpk0^%;VV)3s$XpvuZ3TZ0$%G@DU2(zQD0q_QNlmvB|es1e9NV6
l}2o$rREQ70SC#PgRxGsT{N&$3?@&h$SNhyKUnP!rGn&&7#<UpyNCZHg0q`iQVT6~9I6hj~z^__O#{JQasIaHsgKE?!u2iUUjRY2
rj2=E0xhD^2W)LtPw-V@vn%rG$ncsQ40HcExjXX!-
ZJI7)TQfJAk1Wc&C1d;a|$CXOs|OiS569Ubi(x7$B&K3ux0iDzP;i<9KB^`WKWYjLEB?{E+II1>k&cwt+5A8IP6!BONRr>pdZB`%
&?43~=kMH4fzk7Iu@7)uq8Xg3%YO|LOaJhkOLkzBM$P?hdP?BOCcydLJmtKt#eTvxmZ1aki~|4VVgbZ(11<Okw7Oy`F{T4TbFLgz
qYaRnCLx~(*-hrPzXzjYb{E5Cd-
G6cKke~d%HwXv@M3Ej?#mWRQ{x{7^RSw`PD5=+`o7mx?Wim!1N*sVo20)71a6=7Le=8gp&!9|OsTy$3Kcgc8J7iP@;Pf4%3y>-
x@azWbof^i6>p6Vbp-Tyovt`)zRx`r(>xWxOUbo&?$Cj!rKq@9l3!eELF9z-ski)W-VFkKC2_Q@&GEevuG?rdLtj}^dp=$IKk?8-
kls_$vj=t0);!2bx-;L*PSYx(dQ8y7Fc_ssvu{|%1n8*zLZy1PvFe-bEi`c7jA?-GtqoyifM$Eh%{ctUr3giU-
Q%@|&njA&@QcTMcV3GBkp(cLYrZ=8nqu4?`#atq`!dz+Fo=i<Ml^H1%r_)a;jLvesb(&1@v7&<wfq^pS`!QyM00V7F0A;uC1{{4J
NSUjS|AkOh%h1|}EhL@$<p<6yUEdC5%gUI)k+sSF;2(kDbxukp2EuC2TI5AuoCyj;6L`2x<O2zU~V^UQNut-reJI4{^74pI=K)jH
LhDlC}?3yNBK$k<W$~cwhxNfN#gYe`v==h<o1uAtyr}>oAX+}404S<)|q)&Jbzy5hJA;ye|G$Ux8a2O&y3yk}D&s_w2gI|X(>Ck&
yyrB4yi$5=`sFYS&{{d|c$E)HGPYH>E(rd7FN(*2obgZ~LQj8PvR3nW(L6ETh58;ROr0+_i)Ymj|K+6#)-Lx-
A!PNtM_CeOLWxX3IRl*u`aBFBcwm&3py$1b0AXn|*M|EO}UH>yq`P-hBF(?4A;h^;J@&|+1YALu~3Ow-aU&0mopUaf#1>GMeJ|2K
&uab7_==K1od&qR=-?NqB<U-j{@vh4A$lFSl&d0T5*B|9jr=r`)57Br3G=Q59c8^Q%k-
Fv>$W7f|z+LaDV+oT+W(C7(uRX{+O69P%eCS&|#JQ4hKA@mG0RCR4bHW)=PEFCtmN6sg17aX}JiwE;!v*@ErY$TEhtmd+$;qUhOF
tqmehby3b?i~Z7Y95KJdOe4VGzpPXa*_{C6ZZf1daEOd5;os2Iu$;cQ6Dp9*L5tC$|XqNbcisfTS2kzD8Mz%*6Z$yq8;_3YEvwIj
bk)%TzWO!^>lO-Ww7`o<Z<A0-
N;8G;oL0O+OnFLKlCeYnR#9H>U#W;&Ioe>gRbpKc&iWL{wd+;X&D=%3@@B@^<&n1Yw^f%kM99Rb<{%p^=vSYPkC<XFD>V)X4Rvr+
YONewjimJj}7mr6|H4ajK7Bc^7GHUOb`Fo3^1-
M1Dbe3;9?|KxD27r@n7nuYlFd;Ii8dW(Wa$S*!GyIm5yB{o>T~Ntw~%^rhT*PBA=&zp8TNvqbS%<7k0&m@i@_L#X{bl+&Q$fc&*Z
sqBNDAtC<Nu-=o&9^ISrvWKdwIu2{g;Sm2-PUQg{390ajhSRkohx9T8fcRR*$z7>emQHt!S{OwgKEqq-
w9_Js{Ht8FQbL*C1?3o5;F&cdMUWDE3R@t4hj2|xJR-yns~DCuxDr*tIcZh~Z;-6p_jJC~Ur(z#ExshwX~Xdd;-
StXVdVL;WF>9Szds7I08Kffy26(3DK=HVQ6JJnXy(vV!zyHug&dN(MB1yo-Y(+A^W?JswiHB4Cscy04b4NO1@r-
k8G_QBL_dPrca8oR1Lz5L`lC@4srBlXthMCq5n~Zk)bor`UP6Nub3r%|vgCtPhzpr^9Qhwe)c14pjKfhF;W+U<Y$QZ0kHj~qMk5X
b!XjdW_zXnRrva?=Z7<#UhPVKF=zm1;(s=@&za=|)A-
<9FCE9eJ`M(n1`oF?od3y(Fgh%v0lwI~91$h(dr9TEb3z6RtlzPZiv_=8#{~B*UNP#R_G)Ur9G6|8+&1^!X)AvoD|1Uzs@IN-
7%Y<*9&V}T6j=t{wDlEuDSxVY6by6_Yg8?MSb4nOaC{HkQ84!aCRAYGlL&mM05Z@S$14)hDjnAIXf{3qTe8fN^<e_vUhB7#n;raJ
QWkL-
96DuM@4o0U!$ZvlaV?$^SU0Lj)F#GORxsY8{#;SsSWin*nO0yv$^!8F*i1;&BbZm%|m*GPUB00M7C$_eejh4hIk*GHo7O*18?kQG
;E+Ur}dDusbh{IQ<MPRBs#z?$~p$h4s^ohcMa$7NG<Ox;#6arO#)i;cM!ytCVz(q-
J1Of;F4u((`>wntC*^bDN7?k=C&yYNkap`fKBca^t1qB^qN#Y!dTvo)8V9*{)AcQG~xc04LNW|fA97$Iew8`7eB}lqM5F|!FK_VB
sKf+hyi6XHSATk6$f;*Q42|<w2j?}aR=@IHg`Vmkhlq_@HGw~ya|5ZLaa?J?25mkA~67Cds#2A7Zk>{p&Nqdem#PyRSgoK{~HS#r
`!c#5XBaF?<RHE(~g#G25Xqd-
~|KI@+LRi9{VM|Dnk=6V6Y{_9g8kGwP1CF9WPUk>mh$qaHhzd26@e(8mbWhbWM1q7~A>5YaK=veuuSk%r1!b}zJ-zIsKvZg!&w?P
<BP)28pg_9Jh%+Eb-;`oNNK2nuiq}Z0PLct^jDxx+DG+o<(6%!*<Sa-K@sJ$K(=MfBjG{sS4Ww6>ra_ERXb{RHkRIZ&Q)GxlL<W-
~Ncy1RgruC4j0nZzgAq6pV+cwl)P-IabykGPY6Siz4>d-IsGCrPNSqFVUC?t&z3%&8WRW7qU{ZvFZp<T-
Dh(n>kXQwCV|PeM_fgXHNRkYTit{8-
q%Gt8K2yFwGV=W>Q%$9xeg7u{*t4GPjuNcNze8)G7I5mMUy3?0hNMnTJ&p_t#bDS|#Gmxtiv*Y=>cbd<L{Y+IJrnRJ#sCR@<VnDL
e4(~J3VC9L<VkM27o$%4@;z%{s+XWn0&gC2Cs58|xsyK;^x*#riPs)pQ|2;|LCH!<Uxr7CN*)!Y&YVSw)ye9c2xml~h%ezgj=IuM
_E+O)#he(5H|bI_6hM<_$(z7U9#h8TKkC8O{oDzmK(EZ5Af>%$8)BCTggAAQs)U9lPvY_hawkfohNn;ZB%d*d(hoEcjglxV4ig-T
F%pG>BMdl{2a3uI-K|QUUxr5^H%s7;WPC!u^eP+*XI2l_QuK+T*ppsa-
s4V=yA+g0r%d`}4MUhnq}UjpEy>Tuve=S`X<tbOVC?i&*hWZm1dIA=c)rBw31UepX;T}8DG`r2oWN1v1PSvESds@rvn1lN6)=hki
e%`8o*g?9DL|Ao57<a1JrYRxB8@2y#g6pBnz4HuM2%3`d<kNtx7TAs55F;#Vnv{eFUyKNl%Nms8-
e2)niq+U>@g#xcs*Xk|8<HNp$*(aVir`mF;0ZUWpE;dFGZZl;}IAU|1k@8BnN*WzX43&+<QC>FOoc$Br|e%Y^+uzPh5+BwdtJvLC
4^?qt4L}T!!zne;zYz4S$F>`rP}W*zi%}hhM|T{lCu|Jq>?Fwg16d??K<Mrp6xzKWZ92Qa^qhev-fG7;R7fo>llM{<}cu=!b&-
4^T@31QY-
O00;m803iS<@^vwv5C8x+KL7v}0000;baZepNOW{?L}_zyVRU0?E^v9h8(ojww(<Rb1*^b_l<es~;~0x<kh6V>o%$p2ozsWQLC{L
vJ>|60S|9h3%e}U*1zPl}Kz~D?8nh_-7u-
M5p#P#XLsB9oYQ2ur3WwVjIULRmXNEIF?ySfcEC^<GRTn%6Sh85=Ma9A_%d4<T@~qt0P;KRP7A3iQorWd9yRY8P!tyLlrp@ajjMV
pU%RE!x(|kTpvblOK^XQyc&0AH}QS(+M3%)T!@}fMe_*Dhy6?tX7To$}6ML%DJN$S^Cl9mc!85Sjv!-@x09^hw-t-
4+U1q$#WyB5uLk-`K%4OE@4>b&A3?D{rOvQ`jDepXdWiH@hdI?FS^O8r@#MI<vHNe-
i`q32~bO@Y@J{8i1%YGdO)kVF)w0)_8CfH9SVbvGD12VXr7?jIZ-j>Ox`<43{K;e!{4$D-l>!L#7S;la^!{Ainw4_`cO8Xg@Ve-
#`*etH-@dVX|#BpSc`&2a<p4Ehhhdj8;1@bK`-
@j=_D!3VsIMjPJ7#*^n?u!&kgf6l8X@Rb*?^EHpEym*>td74yb4uEb%X;_v_bUXr4Jxt1FSVd<~ldB{f3%n@8v67|#AWe8y9l@G{
{Mh&GS)Os24nJD(0A)DFHIrS8y~k!rn(~+>8Ot*O2x9?{3m)XNS;?z0n?ZX8W48V6UT;v9Ljb7oy*WkyG|YnNj7R4|3~ggJ&GQrh
J`dAUKupPmpa-
<t!q2oy;xQ0SlTr&Z81<Wiy5vO=&N;P9VQ)Qs@bdoFuD|c^I~xQ_#>rwnQ&MnCp3XeB`6<mQWR4Fkqn~86T&){JU>?J=DF__sxAK
NrrRDoi;MMH{nvz-zS_obfx3wP@#tMRz;WReQaT{2Y9|zWoa&qIm1R-
u7pb(w0K+}=!?Z_C3WaM=<F()||t!@RrF`evfd+nf>&+sx#$U}i`c)nT<tzU|VXC=B^;dx!bn$Rdv9oO?L>sn`TwXy;ntW{gwWTs
0o%wh&wsx|phnuF&Y8`6+0b%5L+iGkz^VOlD!3pKV=By=b#JFLBxTAD0MTnyy#CN7DOOYmXcxlFisnd9ebvi|&ht=6Bn)^Po4g<W
t^-%R7DrxO`ia=~A@h84GH7r1-
I<R;rj*euREO;vu*GmAHEAu!Isy*?bXIEktuFxcV4MY$R#EQ9HF#Y@w#Ys3gKDQ~^=QQHN9N)ZNfjl?V`$Ouw?YMYO21h$t}Q6Sy
`2pM&_O&~y0@l(K)EL~^I@!C}wnr=c3u0a!O>CLTSE<(08*LmU`)UZB9@*M?(4x*en_jy=wz(V709n(M4KGtkuB(37QgIwyp=2mp
i;SHH3DQY2NsJ?v&P3kKw2(sU(j7Wa=0Z^MJjY{?Vg&Ix7N56X=^O7(f8}oo;FspLe_Z)_N5yUScNUuwqd(yhuWWsj0_wAlY8t{#
ipMw)QE^2=JCUl=p*#7pm9UX2$mtm2?uH!n&_Qw>8vO6)Gf%4rc;m;ZAC`W4XaIw5qbT$E0hrY&QR}B^lNAnik*p$^1RZ6l_F)+|
|od=kKWYy;J^^ybSj?*6rG&tdMnI;ig$`-
1QgHdTztxFRQvCxFMPh%|vh%Gk2uAOzJLi|341f`1@`Uv<{#FvnO5a5@PTRh}Z9`nPZ$ibt09j3MT?yajzAgUs~gcqEz)hjiRX&i
DIwW~{85fh?KbmD;lO_T0{%^)X)-Iv`dV8OV_t6@i*J4T<bXWgxA#vzBn@GOJaj<zw>SAA0=XHJSJ8;m#yLoFOIIN{(*zLUp96-
K)nb}U2oVRa<ijKgMV5-eBrkUlVjv#(dor!}sYF37Q5D(M^KilNiim#w!fpCL&}B>V=oh-
d@iA5ehe+C9t5O2iQDcCFI99seU*De>N2sh;#jOh~l~UwpXo?cnp^@iWNDRqxUB2fq#;e(~bqDM`Du29Mb4LxNMO-
9YXGmSqvTJYiGko2#9v!#-sDAF~heb=&FVt-=C<5ucC$EIvZcoyAq|O7tT}vKq0S-
967nM7hi}h<;cAxM_UBqYJEDxcm1kP6Tp_VH!Z8Ql7aAsmDHH`}YPFvghqfa7bAU`^BsXsnmibQQ63^vt<Z*fb*-
zkLBiq6P)aCkN5ALcJ05ofDoDTOIM;~o85AV2hwh)*<!mNe6Y7`pjjmGG8Yk`D`fv6a_=Fq&BWVjH=D6P*Mb^7A2VFM32dr{#}g~
s@q4R$8)fhpNr;%++|6zvX`U~&{0sa`z%Rgq2iT!4I9fCkg4<wIRx){NN&&+6AOgRrvmnU=e#N62@>rK*W$E=Az6Fat<&yXyBSUA
~&my~W)Y)!DDX>iL_<OUm5vFLg83;*LbPqc$o2=12mv55x+P)vfjkyCzyHonJxieWpbsLSd?CR@yl<sbWfs;$_d#x1HTd^(Sv)Y}
ghf2L7WU~fv524>4w4s`4qwPdsIXB7be&nfp5^K%b)o^>n0myXG-
Ldgm+neCin9WL`q8_WllkSaCVJsR?>-WnkywumGRLJ8_Ie;y~D=b;GTlC)cw!b|>osMkfRZIOV%P$8sMJ_YpqMDbr)+mZ$mmo-M_
a_aF7N6QLK6T2XD@t1H7EpWjsZNdBKs_uBNo7BOZbZ~K@d1%p0oM_sneYy6|E8?+8dq<^9Prd;?9<sp#MH)qwql#GZxQWmWG4MsY
xSJMufO%IW=hjHnlTI0lonMIs5X6zYqN>aQi1Onu@y|Xw;^3>olB1fI}d_%i_;MuBO6V!)GR{${IauUj=N4sqZPbpkD;D_!UzTfy
$kf+=MbL?r(|(HG-;dfnbmjYW4q|a0@H-
b9`v<$T%d33x|<XOJ7YkV1Zig4*J6sN@E62*G%1f3vT%Xfcvx3wf+lBZ6>a3V!&sDJ@h@hAGS87KgHIGjXFN7-
LQsNx@Egeht^@{?Eo)U{8D3){gEl~v9PPcqx0jVGP*}HmIY>kV{Avk{vF$a!3f0PEpR&6vDq913t{$7{q)>$LF2Xd4AuPXIk}eD)
>QVZ}I=uc!BM>vM3<lmnF3g<ZT0>k(U(KT=e7adnUv!O9w1I)5LL63Eh>(dX9@EbtmOEozRhi~hfTKJ9R~<DtUmPA|nQkjwCR^2f
6Tmxz@rVR<5reG;nJA14p(_AU?ej&^-D|4vpE<qgLPxuzQuQoHNY)S_77NQCcoo1-v9_qD6o~;%0ue>nl#m&Ix=vz|D7(-
VR`5w?n8boT4NwZj05fHQVshFIab_DaONz1z2FIkfF=@DJNGyjq%<<`1WR|2ASGnQIOgI)oeCjpp#po0iN8*<x-smx^Y`<6pc!h-
saH$g(JHNy;+#U_qG1RF!!}XG^-rBk5O%YeuDo;b7@k?}fD3Ml3cqsu?F%glAwno4`2%0aJl!_N&Hs|hchm>hRnF)-
96vEYg;?@@1Ax9~37{j7POj3Yx@(z$+o`t&~-R--{nR7u0)0<?@n-{y^-@uyOet#pUhHu(Ems`i@8J3?r@rDPP-
Bp~-Q99nqcyIT#M-T4Lcuuu-qo})eHVi21rqT_tr8PnF2PsxbWqrHv*B7Zxdv|ux(?@Atf@_<!sf)o3Ccij=ea`_j!J?cuMvjnFy
#w<uO9-
T0$*z4P7(5Wb2b1Imu}V4cB>;7CX{I^(Q&C8BJ&m(%`+PJf9abpI#?j&sAiyI4Fzrr{Y&D!v_gUc8AwVjwE&=~x5uLe}?F2(T;FD
?8F#GtlMnu5=yvXaNyMj5M;xW(bzlN`Wc>VYM_21}#2MAHFf}GYj_3qtxs=8KFU|6iMIgmb36SO_6IbFY)qd#KRrF!`?P+TcaDXT
ZIQ}FQIUd9oDg6(i;80G(rw>65b_!t}au?T-
PXQ2FHulOq4ss3t&2{sw_g5`2JSRN@9mh&um;Y`0|rt>ivYyn0Y?&Z@eOfn;zB!zEP(Nex>r)|N8qaVxs=s4-
NTxa5P<$0flk9?R789XU_2P<vkC~>maGdht0D#t|!Nh<fVCw)B>V;Y_EY;p(VEIRg(=)}RAd=bZKn%5C76r;5Ugo2?atkL)i@rHt
OkjAA@tDl6BX<>lN3!?^b7d=oxMb&mL=_z;GK#L9vHDZV-Ed-&71)`P)D;kYNg`^v5YjlBNutlLaRR-gp6jVWZ>2jGS6*iQv#fPA
4A3KB&;1TRCi^1podW0!njn;tU#e^<k9kHFhcLn$W3k&esCK#QVQ$2tdAPIR-
3x=hG^*AvLaCBqk#(DkE<?A2+^}E+UzWzrzkditA<xuZWzyIw|fBa#ncV5(4JcxL2|D)|e#Fs0ljn2Yi&Mm#SL)Q~DZ3amW$*)n>
b)*+9F$@@>5HSt){rk^<`OlyJFw`4|H7|xbKi(TgTk%U<-+)Lot3-ix3?EwY_P1-
Ao3rVd{zQQ_$Pj1=FJXo^6YX~eQHQg6={gsh$E0&xoNFRJMudNY|MUW2lrNSwo~kUuNcw46Fd1;ua$<z{VGl5acrE2n35Qcxv(0;
s*Wm4Un7K}a&`3@+k|AbDX4gX$k64+^vk)%=w;W*A(ar+$9~L~2^T?~ix=<u?PeZIz(^ks_E$!V(ni=m5uDA^`y}OSX=v)v7Dlg|
d-pS6X9rQ!UM<)*ZfVrEv52|*L-C_III)`>wN&L{nuZy${XFPzhF<nb)urzt1=gS@~nOI$+QdgF4dnMuaD)zv2>*l1V^HTr|{-
((`0K|w_rCNDY5Mvg$diCjE^~rLDvoklu(Cd`T#7!SZD#e8U8?zxE>j_3@KHyRu#fpL&yo#cZ-
a=8D(U_D$FBTLbXm>K{p`b^MlzUXSaD-
0{8+NM0QiBz=6Vn>Ls^>yG&a2liotfrDl>@b07)4J<kb>Hd6Ybm)T@e{KiaQq9EOn0hH}>(ag^c|SEgdm=yM)|Rnk<s$w)5ULG=$
k)+<ODVro;p^3B-gcko~N-s+TE0Nt3cVX)h@sWY?$aQuK%ho{oQcLonsja@^(&_FC)7=}2<X^or}gK-
7)%${90x6U8C<I3y64zI#;A%;wOBAGdF9g+!ofg(LIM@sLrrr?ujS<FD|x?v5!DDXV79R%gD3$f&g2R1-
zoi`zDA6aC`>O_(~%n$k%LlF)=&wW>5hzc^S09|^bF^T+aDr-
f@R4c0lDgCqb}oXp{wgHXJJ)7e9ZqqUS$9NP7%A68MT)|s8ZoZh^H;;fKACA$gTR&=|hD-
T`PX@x%N<g_Q4q)al{dooD90d7P=NT+Cn*`P}V_rY;yPk`vi+i#0Ju2T}?Nn5`U)8soIh%R^GQNp+oC34A(In_ea)kZl3I&~*zEw
>o)$mzXaG%P!GY3et{2%n^|d?y#(x?-CX9(M%=W=Pr-<mVm5TWP&R{Na9fa%w$zkCQU0#c!SjTlpnj3nt>|G|h-
i``2~fZlAFDqux)H@DX-p))R!0NrJa-==Z@ckqi4Q1gDet-}i1+yC~l^%^h62fokg770@y-
*OkzSnUyLtf%t{P%8rW~c2A~Ezj}W3e-
|n~%@27dH{!@a{v^Tn15U{xijTYvy2Zwa<>z=(@n29&0|XQR000O8001EX000000ssI2000005C8xGNOW{?FJE72ZfSI1UoLQY0{
~D<0Rj{Q6aWAK2mk;8Api*$4=;8E0021;000~S0000000000005)`00000LUn0uWMy(tVP|D8L2h(uR%vo|b5LPtWiD`eP)h*<6a
y3h000O8001EX1<AGKlmY+%DhB`n9RL6T0000000000qyex5002UDX>4R=a!_GsWiLc&b7OULb7^mGP+@0fE^v8JO928D0~7!N00
;m803iTCUN*4*0{{Sx3jhEb00000000000001_0e=So077+XY-
D9}P+@0fFG+55bYX04P+@0fE^v8JO928D0~7!N00;m803iTev}(1l3;+OaHvj+^00000000000001_0k#VO077+XY-
D9}P+@0fFHK=-
Zct%oWiD`eP)h*<6ay3h000O8001EX000000ssI2000007XSbN0000000000qyd^3002UDX>4R=a!_GsWiMY}X>MtBUtcb8c~DCM
0u%!j000080000X0CiyKmz)g%07Fp#03QGV00000000000HguY7ytl5b#!!ZZZAV&Y;0m-V{1ZnbaZcSNMUYdY-MsTaCuNm0Rj{Q
6aWAK2mk;8Aplj8(annj005E)000~S0000000000005)`swMycLUnX>Z*DJ1Zg6#ULUnX>Z*E9oZe(m_axQRrP)h*<6ay3h000O8
001EXdBG;|*#`gsNFD$H9{>OV0000000000qycX!002UDbaZcSFG+55bYX04P+@s&Z((FeVQyq>WpXZXc~DCM0u%!j000080000X
0000000IC20000001^NI00000000000HgthF#rHUb#!!ZZZBV7X>MtBUtcb8c~DCM0u%!j000080000X0L~Q+nfw?40Gn3;00;m8
00000000000Hgu8F#rHVZ*FsRE^v8JO928D0~7!N00;m803iS<@^vwv5C8x+KL7v}00000000000001_0oh6b07!Ina4$%7bZ|sz
b8umFV`wgLc~DCM0u%!j000080000X0000000IC20000001yBG00000000000Hgt`TL1t^baZepUtei%X>?y-
E^v8JO9ci10000C01N;@0{{TpTL1t600
"""

def __cubkit_bootstrap__():
    # CubKit import-debug: this function is generated by CubKit.
    # It prepares bundled files before the real MCUB module code below runs.
    import base64
    import hashlib
    import os
    import sys
    import types
    import zipfile
    from pathlib import Path

    # CubKit import-debug: decode the embedded base85 zip payload.
    data = base64.b85decode("".join(__cubkit_bundle_b85__.split()).encode("ascii"))
    digest = hashlib.sha256(data).hexdigest()
    # CubKit import-debug: fail fast if the embedded payload was corrupted.
    if digest != __cubkit_bundle_sha256__:
        raise RuntimeError("CubKit embedded bundle checksum mismatch")

    # CubKit import-debug: cache extraction avoids rewriting helper files on every import.
    cache_root = Path(os.environ.get("CUBKIT_CACHE_DIR", Path.home() / ".cache" / "cubkit"))
    bundle_dir = cache_root / __cubkit_module_id__ / digest
    marker = bundle_dir / ".cubkit-extracted"
    if not marker.exists():
        bundle_dir.mkdir(parents=True, exist_ok=True)
        archive_path = bundle_dir / "bundle.zip"
        archive_path.write_bytes(data)
        with zipfile.ZipFile(archive_path) as archive:
            archive.extractall(bundle_dir)
        marker.write_text(digest, encoding="utf-8")

    # CubKit import-debug: expose extracted top-level files for normal absolute imports.
    bundle_path = str(bundle_dir)
    if bundle_path not in sys.path:
        sys.path.insert(0, bundle_path)

    # CubKit import-debug: build private package search paths for `from .utils import ...`.
    relative_import_paths = [bundle_path]
    for package_dir in reversed(__cubkit_package_dirs__):
        package_path = bundle_dir / package_dir
        if package_path.is_dir():
            relative_import_paths.insert(0, str(package_path))

    # CubKit import-debug: mark the generated main module as package-like.
    # This prevents accidental imports from global MCUB packages named `utils`, `lib`, etc.
    module_globals = globals()
    module_globals["__path__"] = relative_import_paths
    module_globals["__package__"] = module_globals.get("__name__", __cubkit_module_id__)
    module_spec = module_globals.get("__spec__")
    if module_spec is not None:
        module_spec.submodule_search_locations = relative_import_paths

    # CubKit import-debug: expose vendored libraries through `from cubkit.lib import name`.
    lib_path = bundle_dir / __cubkit_lib_dir__
    if lib_path.is_dir():
        lib_path_str = str(lib_path)
        if lib_path_str not in sys.path:
            sys.path.insert(0, lib_path_str)

        cubkit_pkg = sys.modules.get("cubkit")
        if cubkit_pkg is None:
            cubkit_pkg = types.ModuleType("cubkit")
            sys.modules["cubkit"] = cubkit_pkg
        if not hasattr(cubkit_pkg, "__path__"):
            cubkit_pkg.__path__ = []

        lib_pkg = sys.modules.get("cubkit.lib")
        if lib_pkg is None:
            lib_pkg = types.ModuleType("cubkit.lib")
            sys.modules["cubkit.lib"] = lib_pkg
        lib_pkg.__path__ = [lib_path_str]
        lib_pkg.__package__ = "cubkit"
        setattr(cubkit_pkg, "lib", lib_pkg)

__cubkit_bootstrap__()
del __cubkit_bootstrap__

# ---- CubKit entrypoint: VectorMain.py ----
# ‼️‼️‼️‼️ THE MODULE IS A PORT WITH HEROKU ‼️‼️‼️‼️
# ====================================================================================================================
# Repo MCUB - https://github.com/hairpin01/repo-MCUB-fork
# MCUB - https://github.com/hairpin01/MCUB-fork
# ====================================================================================================================
#   ██████╗  ██████╗ ██╗   ██╗███╗   ███╗ ██████╗ ██████╗ ██╗   ██╗██╗     ███████╗███████╗
#  ██╔════╝ ██╔═══██╗╚██╗ ██╔╝████╗ ████║██╔═══██╗██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
#  ██║  ███╗██║   ██║ ╚████╔╝ ██╔████╔██║██║   ██║██║  ██║██║   ██║██║     █████╗  ███████╗
#  ██║   ██║██║   ██║  ╚██╔╝  ██║╚██╔╝██║██║   ██║██║  ██║██║   ██║██║     ██╔══╝  ╚════██║
#  ╚██████╔╝╚██████╔╝   ██║   ██║ ╚═╝ ██║╚██████╔╝██████╔╝╚██████╔╝███████╗███████╗███████║
#   ╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝
#
#   OFFICIAL USERNAMES: @goymodules | @samsepi0l_ovf
#   MODULE: Vector (PORT FOR MCUB @Hairpin00)
#
#   THIS MODULE IS LICENSED UNDER GNU AGPLv3, PROTECTED AGAINST UNAUTHORIZED COPYING/RESALE,
#   AND ITS ORIGINAL AUTHORSHIP BELONGS TO @samsepi0l_ovf.
#   ALL OFFICIAL UPDATES, RELEASE NOTES, AND PATCHES ARE PUBLISHED IN THE TELEGRAM CHANNEL @goymodules.
# ====================================================================================================================
# scop: kernel min v1.4.6


import hashlib
import inspect
import logging
import sys
from typing import Any
from urllib.parse import quote

# api
from core.lib.loader.module_base import ModuleBase, command, loop
from core.lib.loader.module_config import (
    Boolean,
    ConfigValue,
    Integer,
    ModuleConfig,
)
from core.lib.types import Event

# local
from .Const import (
    LOADING_BANNER,
    _esc,
)
from .Button.CallbackButtonHandler import VectorCallbackButtonHandlerMixin
from .Button.InputButtonHandler import VectorInputButtonHandlerMixin
from .Button.InstallPayloadHandler import VectorInstallPayloadHandlerMixin
from .Http.HttpDispatch import VectorHttpDispatchMixin
from .BuilderPage.AntiVirusPage import VectorAntiVirusPageMixin
from .BuilderPage.DiscussionPage import VectorDiscussionPageMixin
from .BuilderPage.InstallPage import VectorInstallPageMixin
from .BuilderPage.MainPage import VectorMainPageMixin

LOG = logging.getLogger("VectorMonolith")
LOG.setLevel(logging.DEBUG)

class Vector(
    VectorHttpDispatchMixin,
    VectorInstallPageMixin,
    VectorMainPageMixin,
    VectorDiscussionPageMixin,
    VectorAntiVirusPageMixin,
    VectorInputButtonHandlerMixin,
    VectorInstallPayloadHandlerMixin,
    VectorCallbackButtonHandlerMixin,
    ModuleBase,
):
    name = "Vector"
    version = "2.4.4"
    author = "@samsepi0l_ovf"
    description = {
        "en": "Vector module registry browser.\nhttps://www.0xvector.lol",
        "ru": "Бpayзep peecтpa мoдyлeй Vector.\nhttps://www.0xvector.lol",
        "uk": "Браузер реєстру модулів Vector.\nhttps://www.0xvector.lol",
    }
    dependencies = ["aiohttp"]
    banner_url = "https://raw.githubusercontent.com/sepiol026-wq/GoyModules/refs/heads/main/assets/vector.png"

    config = ModuleConfig(
        ConfigValue(
            "limit",
            30,
            description="Search output limits.",
            validator=Integer(min=1, max=100),
        ),
        ConfigValue(
            "max_batch",
            50,
            description="Max modules per batch install.",
            validator=Integer(min=1, max=100),
        ),
        ConfigValue(
            "auto_update_notify",
            True,
            description="Notify me about module updates (hashing-based).",
            validator=Boolean(),
        ),
        ConfigValue(
            "VectorInstall",
            True,
            description="Enable Vector Install",
            validator=Boolean(),
        ),
    )
    from .Const import (
        ICONS,
        _ierrs,
        strings_i18n,
    )

    strings: dict[str, dict[str, str]] = strings_i18n
    _cached_groups: dict[str, list[dict[str, Any]]] = {}
    seccache: dict[str, dict[str, Any]] = {}


    @command(
        "vector",
        doc_en="<query> \u2014 search modules in Vector.",
        doc_ru="<\u0437\u0430\u043f\u0440\u043e\u0441> \u2014 \u043f\u043e\u0438\u0441\u043a \u043c\u043e\u0434\u0443\u043b\u0435\u0439 \u0432 Vector.",
        doc_uk="<запит> — пошук модулів у Vector.",
    )
    async def vectorcmd(self, event: Event) -> None:
        q = event.text.split(maxsplit=1)
        q = q[1].strip() if len(q) > 1 else ""
        LOG.info("vectorcmd: query=%r", q)
        if not q:
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_err_empty', p='<code>.</code>')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        if len(q) > 120:
            await event.edit(
                f"{self.ICONS['warn']} <b>{self.strings('v_err_len')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return

        success, form_msg = await self.subinline.form(
            event.chat_id,
            f"{self.ICONS['search']} <b>{self.strings('v_sending')}</b>",
            buttons=[
                [
                    self.Button.inline(
                        "\u2800",
                        self.cb_vector_search,
                        data=self._cb_data("v_search", q=q),
                    )
                ]
            ],
            media=LOADING_BANNER,
            ttl=300,
        )
        if success and form_msg:
            await form_msg.click(0)
        else:
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_err_api')}</b>",
                parse_mode="html",
                link_preview=False,
            )

    def _hash_module_source(self, module_instance: Any | None = None) -> str:
        target = module_instance or self
        module = sys.modules.get(target.__class__.__module__)
        loader = getattr(module, "__loader__", None)
        if loader and hasattr(loader, "get_source"):
            try:
                source = loader.get_source(target.__class__.__module__)
                if source:
                    return hashlib.sha256(source.encode("utf-8")).hexdigest()
            except Exception as e:
                LOG.debug("_hash_module_source: loader.get_source failed: %r", e)

        if module:
            try:
                source = inspect.getsource(module)
                return hashlib.sha256(source.encode("utf-8")).hexdigest()
            except Exception as e:
                LOG.debug("_hash_module_source: inspect.getsource failed: %r", e)
        return ""

    async def _sync_installed_modules(self) -> bool:
        token = await self._get_active_token()
        if not token:
            return False
        modules_data: list[dict[str, str]] = []
        lang = self._detect_lang_suffix()
        for collection_name in ("loaded_modules", "system_modules"):
            collection = getattr(self.kernel, collection_name, {}) or {}
            for module in collection.values():
                module_hash = self._hash_module_source(module)
                if not module_hash:
                    continue
                modules_data.append(
                    {
                        "class_name": module.__class__.__name__,
                        "contentHash": module_hash,
                        "language": lang,
                    }
                )
        if not modules_data:
            return False
        res = await self._net_req(
            "PUT",
            "/api/users/me/modules",
            token=token,
            json_data={"modules": modules_data},
            timeout=30,
        )
        return bool(res and res.get("ok"))

    @loop(interval=86_400, autostart=True)
    async def _sync_modules_keeper(self) -> None:
        if not self.config["auto_update_notify"]:
            return
        try:
            await self._sync_installed_modules()
        except Exception as e:
            LOG.debug("_sync_modules_keeper: failed: %r", e)

    async def _install_vector_update(self, event: Event, dl_url: str) -> None:
        await event.edit(
            f"{self.ICONS['search']} <b>{self.strings('v_upd_req')}</b>",
            parse_mode="html",
            link_preview=False,
        )
        res, _errors = await self._safe_install("Vector", dl_url, notify=False)
        text = (
            f"{self.ICONS['safe']} <b>{self.strings('v_upd_ok')}</b>"
            if res == 1
            else f"{self.ICONS['error']} <b>{self.strings('v_upd_err')}</b>"
        )
        await event.edit(text, parse_mode="html", link_preview=False)

    @command(
        "vecupdate",
        doc_en="[-f|--force] \u2014 update Vector module.",
        doc_ru="[-f|--force] \u2014 \u043e\u0431\u043d\u043e\u0432\u0438\u0442\u044c \u043c\u043e\u0434\u0443\u043b\u044c Vector.",
        doc_uk="[-f|--force] — оновити модуль Vector.",
    )
    async def vecupdate(self, event: Event) -> None:
        args = event.text.split(maxsplit=1)
        args_str = args[1].strip() if len(args) > 1 else ""
        force = "-f" in args_str or "--force" in args_str
        LOG.info("vecupdate: force=%s", force)

        dl_url = "https://raw.githubusercontent.com/hairpin01/repo-MCUB-fork/refs/heads/main/Vector-MCUB-repo.py"
        if force:
            await self._install_vector_update(event, dl_url)
            return

        await event.edit(
            f"{self.ICONS['search']} <b>{self.strings('v_upd_check')}</b>",
            parse_mode="html",
            link_preview=False,
        )

        remote_bytes = await self._net_req("GET", dl_url, as_bytes=True, timeout=30)
        if not remote_bytes:
            LOG.warning("vecupdate: remote source unavailable, installing anyway")
            await self._install_vector_update(event, dl_url)
            return

        remote_hash = hashlib.sha256(remote_bytes).hexdigest()
        local_hash = self._hash_module_source()
        if local_hash:
            LOG.debug(
                "vecupdate: local_hash=%s remote_hash=%s",
                local_hash[:16],
                remote_hash[:16],
            )
        else:
            LOG.warning("vecupdate: local source hash unavailable, assuming update needed")

        if local_hash and local_hash == remote_hash:
            await self.subinline.form(
                event.chat_id,
                f"{self.ICONS['search']} <b>{self.strings('v_upd_req')}</b>\n\n{self.strings('v_upd_same')}",
                buttons=[
                    [
                        self.Button.inline(
                            self.strings["v_upd_force_btn"],
                            self.force_update,
                            data=self._cb_data("force_upd", url=dl_url),
                        ),
                        self.Button.inline(
                            self.strings["v_upd_cancel"],
                            self.cb_dummy,
                            data=self._cb_data("cancel_update"),
                        ),
                    ]
                ],
                parse_mode="html",
            )
            return

        await self._install_vector_update(event, dl_url)


    @command(
        "vecme",
        doc_en="\u2014 open Vector as Telegram Mini App.",
        doc_ru="\u2014 \u043e\u0442\u043a\u0440\u044b\u0442\u044c Vector \u043a\u0430\u043a Telegram Mini App.",
        doc_uk="— відкрити Vector як Telegram Mini App.",
    )
    async def vecmecmd(self, event: Event) -> None:
        bot_info = await self._net_req("GET", "/api/tg-bot")
        bot_uname = (bot_info or {}).get("username", "").strip().lstrip("@")
        if not bot_uname:
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_err_api')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        link = f"https://t.me/{bot_uname}/vector"
        text = (
            f"{self.ICONS['shield']} <b>{self.strings('v_miniapp_title')}</b>\n\n"
            f"{self.strings('v_miniapp_body')}"
        )
        await self.subinline.form(
            event.chat_id,
            text,
            buttons=[[self.Button.url(self.strings("v_miniapp_btn"), link)]],
            parse_mode="html",
        )

    @command(
        "vecdl",
        doc_en="<slug or URL> \u2014 download and install entire module collection from Vector.",
        doc_ru="<slug \u0438\u043b\u0438 \u0441\u0441\u044b\u043b\u043a\u0430> \u2014 \u0441\u043a\u0430\u0447\u0430\u0442\u044c \u0438 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044e \u0438\u0437 Vector.",
        doc_uk="<slug або URL> — завантажити та встановити колекцію з Vector.",
    )
    async def vecdlcmd(self, event: Event) -> None:
        args = event.text.split(maxsplit=1)
        raw_arg = args[1].strip() if len(args) > 1 else ""
        slug = (
            raw_arg.split("/collections/")[-1].split("/")[0].split("?")[0]
            if "/collections/" in raw_arg
            else raw_arg
        )
        LOG.info("vecdl: slug=%r", slug)
        if not slug:
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_vecdl_usage', p='<code>.</code>')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        token = await self._get_active_token()
        if not token:
            await event.edit(
                self.bannote
                or f"{self.ICONS['error']} <b>{self.strings('v_err_api')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        raw = await self._net_req(
            "GET", f"/api/collections/{quote(slug, safe='')}", token=token
        )
        if not raw or not raw.get("ok"):
            await event.edit(
                f"{self.ICONS['error']} <b>{self.strings('v_dlcoll_not_found')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        col = raw["collection"]
        modules = [
            entry["module"]
            for entry in (col.get("modules") or [])
            if entry.get("module")
        ]
        if not modules:
            await event.edit(
                f"{self.ICONS['warn']} <b>{self.strings('v_dlcoll_empty')}</b>",
                parse_mode="html",
                link_preview=False,
            )
            return
        await event.edit(
            f"{self.ICONS['search']} <b>{self.strings('v_sending')}</b>",
            parse_mode="html",
            link_preview=False,
        )
        max_batch = int(self.config["max_batch"])
        total_orig = len(modules)
        if total_orig > max_batch:
            modules = modules[:max_batch]
        col_name = col.get("name", slug)
        await self._safe_edit(
            event,
            f"{self.ICONS['modules_list']} {self.strings('v_dlcoll_hdr', name=_esc(col_name))}\n{self.strings('v_dlcoll_count', count=len(modules))}",
            [
                [
                    self.Button.inline(
                        self.strings["v_btn_dl"],
                        self.cb_vecdl_install,
                        data=self._cb_data(
                            "vecdl_install",
                            modules=modules,
                            col_name=col_name,
                            total_orig=total_orig,
                            max_batch=max_batch,
                        ),
                    )
                ]
            ],
        )
